export const Errors = {
  INVALID_LISTENER: "INVALID_LISTENER",
  INVALID_WEBPLAYBACK: "INVALID_WEBPLAYBACK",
  NO_BODY: "NO_BODY",
  NO_EVENT: "NO_EVENT",
  INVALID_OAUTH: "INVALID_OAUTH",
  MISSING_IFRAME: "MISSING_IFRAME",
  AUTOPLAY_FAILED: "AUTOPLAY_FAILED",
} as const;
