/* tslint:disable */
/* eslint-disable */
/**
 * Spotify Web API with fixes and improvements from sonallux
 * You can use Spotify\'s Web API to discover music and podcasts, manage your Spotify library, control audio playback, and much more. Browse our available Web API endpoints using the sidebar at left, or via the navigation bar on top of this page on smaller screens.  In order to make successful Web API requests your app will need a valid access token. One can be obtained through <a href=\"https://developer.spotify.com/documentation/general/guides/authorization-guide/\">OAuth 2.0</a>.  The base URI for all Web API requests is `https://api.spotify.com/v1`.  Need help? See our <a href=\"https://developer.spotify.com/documentation/web-api/guides/\">Web API guides</a> for more information, or visit the <a href=\"https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer\">Spotify for Developers community forum</a> to ask questions and connect with other developers.
 *
 * The version of the OpenAPI document: 2025.5.18
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
  ArtistObject,
  FollowArtistsUsersRequest,
  FollowTypeEnum,
  GetAnAlbum401Response,
  GetAnArtistsTopTracks200Response,
  GetFollowed200Response,
  GetFollowTypeEnum,
  GetMultipleArtists200Response,
  PagingArtistDiscographyAlbumObject,
  PagingArtistObject,
  UnfollowArtistsUsersRequest,
} from "../models/index";
import * as runtime from "../runtime";

export interface ArtistsApiCheckCurrentUserFollowsRequest {
  type: FollowTypeEnum;
  ids: string;
}

export interface ArtistsApiFollowArtistsUsersOperationRequest {
  type: FollowTypeEnum;
  ids: string;
  followArtistsUsersRequest?: FollowArtistsUsersRequest;
}

export interface ArtistsApiGetAnArtistRequest {
  id: string;
}

export interface ArtistsApiGetAnArtistsAlbumsRequest {
  id: string;
  includeGroups?: string;
  market?: string;
  limit?: number;
  offset?: number;
}

export interface ArtistsApiGetAnArtistsRelatedArtistsRequest {
  id: string;
}

export interface ArtistsApiGetAnArtistsTopTracksRequest {
  id: string;
  market?: string;
}

export interface ArtistsApiGetFollowedRequest {
  type: GetFollowTypeEnum;
  after?: string;
  limit?: number;
}

export interface ArtistsApiGetMultipleArtistsRequest {
  ids: string;
}

export interface ArtistsApiGetUsersTopArtistsRequest {
  timeRange?: string;
  limit?: number;
  offset?: number;
}

export interface ArtistsApiUnfollowArtistsUsersOperationRequest {
  type: FollowTypeEnum;
  ids: string;
  unfollowArtistsUsersRequest?: UnfollowArtistsUsersRequest;
}

/**
 *
 */
export class ArtistsApi extends runtime.BaseAPI {
  /**
   * Check to see if the current user is following one or more artists or other Spotify users.
   * Check If User Follows Artists or Users
   */
  async checkCurrentUserFollowsRaw(
    requestParameters: ArtistsApiCheckCurrentUserFollowsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<boolean>>> {
    if (requestParameters["type"] == null) {
      throw new runtime.RequiredError(
        "type",
        'Required parameter "type" was null or undefined when calling checkCurrentUserFollows().',
      );
    }

    if (requestParameters["ids"] == null) {
      throw new runtime.RequiredError(
        "ids",
        'Required parameter "ids" was null or undefined when calling checkCurrentUserFollows().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["type"] != null) {
      queryParameters["type"] = requestParameters["type"];
    }

    if (requestParameters["ids"] != null) {
      queryParameters["ids"] = requestParameters["ids"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-follow-read"],
      );
    }

    let urlPath = `/me/following/contains`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse<any>(response);
  }

  /**
   * Check to see if the current user is following one or more artists or other Spotify users.
   * Check If User Follows Artists or Users
   */
  async checkCurrentUserFollows(
    requestParameters: ArtistsApiCheckCurrentUserFollowsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<boolean>> {
    const response = await this.checkCurrentUserFollowsRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Add the current user as a follower of one or more artists or other Spotify users.
   * Follow Artists or Users
   */
  async followArtistsUsersRaw(
    requestParameters: ArtistsApiFollowArtistsUsersOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["type"] == null) {
      throw new runtime.RequiredError(
        "type",
        'Required parameter "type" was null or undefined when calling followArtistsUsers().',
      );
    }

    if (requestParameters["ids"] == null) {
      throw new runtime.RequiredError(
        "ids",
        'Required parameter "ids" was null or undefined when calling followArtistsUsers().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["type"] != null) {
      queryParameters["type"] = requestParameters["type"];
    }

    if (requestParameters["ids"] != null) {
      queryParameters["ids"] = requestParameters["ids"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-follow-modify"],
      );
    }

    let urlPath = `/me/following`;

    const response = await this.request(
      {
        path: urlPath,
        method: "PUT",
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters["followArtistsUsersRequest"],
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Add the current user as a follower of one or more artists or other Spotify users.
   * Follow Artists or Users
   */
  async followArtistsUsers(
    requestParameters: ArtistsApiFollowArtistsUsersOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.followArtistsUsersRaw(requestParameters, initOverrides);
  }

  /**
   * Get Spotify catalog information for a single artist identified by their unique Spotify ID.
   * Get Artist
   */
  async getAnArtistRaw(
    requestParameters: ArtistsApiGetAnArtistRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ArtistObject>> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling getAnArtist().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        [],
      );
    }

    let urlPath = `/artists/{id}`;
    urlPath = urlPath.replace(
      `{${"id"}}`,
      encodeURIComponent(String(requestParameters["id"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get Spotify catalog information for a single artist identified by their unique Spotify ID.
   * Get Artist
   */
  async getAnArtist(
    requestParameters: ArtistsApiGetAnArtistRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ArtistObject> {
    const response = await this.getAnArtistRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Get Spotify catalog information about an artist\'s albums.
   * Get Artist\'s Albums
   */
  async getAnArtistsAlbumsRaw(
    requestParameters: ArtistsApiGetAnArtistsAlbumsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PagingArtistDiscographyAlbumObject>> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling getAnArtistsAlbums().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["includeGroups"] != null) {
      queryParameters["include_groups"] = requestParameters["includeGroups"];
    }

    if (requestParameters["market"] != null) {
      queryParameters["market"] = requestParameters["market"];
    }

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    if (requestParameters["offset"] != null) {
      queryParameters["offset"] = requestParameters["offset"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        [],
      );
    }

    let urlPath = `/artists/{id}/albums`;
    urlPath = urlPath.replace(
      `{${"id"}}`,
      encodeURIComponent(String(requestParameters["id"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get Spotify catalog information about an artist\'s albums.
   * Get Artist\'s Albums
   */
  async getAnArtistsAlbums(
    requestParameters: ArtistsApiGetAnArtistsAlbumsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PagingArtistDiscographyAlbumObject> {
    const response = await this.getAnArtistsAlbumsRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Get Spotify catalog information about artists similar to a given artist. Similarity is based on analysis of the Spotify community\'s listening history.
   * Get Artist\'s Related Artists
   * @deprecated
   */
  async getAnArtistsRelatedArtistsRaw(
    requestParameters: ArtistsApiGetAnArtistsRelatedArtistsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<GetMultipleArtists200Response>> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling getAnArtistsRelatedArtists().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        [],
      );
    }

    let urlPath = `/artists/{id}/related-artists`;
    urlPath = urlPath.replace(
      `{${"id"}}`,
      encodeURIComponent(String(requestParameters["id"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get Spotify catalog information about artists similar to a given artist. Similarity is based on analysis of the Spotify community\'s listening history.
   * Get Artist\'s Related Artists
   * @deprecated
   */
  async getAnArtistsRelatedArtists(
    requestParameters: ArtistsApiGetAnArtistsRelatedArtistsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<GetMultipleArtists200Response> {
    const response = await this.getAnArtistsRelatedArtistsRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Get Spotify catalog information about an artist\'s top tracks by country.
   * Get Artist\'s Top Tracks
   */
  async getAnArtistsTopTracksRaw(
    requestParameters: ArtistsApiGetAnArtistsTopTracksRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<GetAnArtistsTopTracks200Response>> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling getAnArtistsTopTracks().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["market"] != null) {
      queryParameters["market"] = requestParameters["market"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        [],
      );
    }

    let urlPath = `/artists/{id}/top-tracks`;
    urlPath = urlPath.replace(
      `{${"id"}}`,
      encodeURIComponent(String(requestParameters["id"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get Spotify catalog information about an artist\'s top tracks by country.
   * Get Artist\'s Top Tracks
   */
  async getAnArtistsTopTracks(
    requestParameters: ArtistsApiGetAnArtistsTopTracksRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<GetAnArtistsTopTracks200Response> {
    const response = await this.getAnArtistsTopTracksRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Get the current user\'s followed artists.
   * Get Followed Artists
   */
  async getFollowedRaw(
    requestParameters: ArtistsApiGetFollowedRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<GetFollowed200Response>> {
    if (requestParameters["type"] == null) {
      throw new runtime.RequiredError(
        "type",
        'Required parameter "type" was null or undefined when calling getFollowed().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["type"] != null) {
      queryParameters["type"] = requestParameters["type"];
    }

    if (requestParameters["after"] != null) {
      queryParameters["after"] = requestParameters["after"];
    }

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-follow-read"],
      );
    }

    let urlPath = `/me/following`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get the current user\'s followed artists.
   * Get Followed Artists
   */
  async getFollowed(
    requestParameters: ArtistsApiGetFollowedRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<GetFollowed200Response> {
    const response = await this.getFollowedRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Get Spotify catalog information for several artists based on their Spotify IDs.
   * Get Several Artists
   */
  async getMultipleArtistsRaw(
    requestParameters: ArtistsApiGetMultipleArtistsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<GetMultipleArtists200Response>> {
    if (requestParameters["ids"] == null) {
      throw new runtime.RequiredError(
        "ids",
        'Required parameter "ids" was null or undefined when calling getMultipleArtists().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["ids"] != null) {
      queryParameters["ids"] = requestParameters["ids"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        [],
      );
    }

    let urlPath = `/artists`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get Spotify catalog information for several artists based on their Spotify IDs.
   * Get Several Artists
   */
  async getMultipleArtists(
    requestParameters: ArtistsApiGetMultipleArtistsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<GetMultipleArtists200Response> {
    const response = await this.getMultipleArtistsRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Get the current user\'s top artists based on calculated affinity.
   * Get User\'s Top Artists
   */
  async getUsersTopArtistsRaw(
    requestParameters: ArtistsApiGetUsersTopArtistsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PagingArtistObject>> {
    const queryParameters: any = {};

    if (requestParameters["timeRange"] != null) {
      queryParameters["time_range"] = requestParameters["timeRange"];
    }

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    if (requestParameters["offset"] != null) {
      queryParameters["offset"] = requestParameters["offset"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-top-read"],
      );
    }

    let urlPath = `/me/top/artists`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get the current user\'s top artists based on calculated affinity.
   * Get User\'s Top Artists
   */
  async getUsersTopArtists(
    requestParameters: ArtistsApiGetUsersTopArtistsRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PagingArtistObject> {
    const response = await this.getUsersTopArtistsRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Remove the current user as a follower of one or more artists or other Spotify users.
   * Unfollow Artists or Users
   */
  async unfollowArtistsUsersRaw(
    requestParameters: ArtistsApiUnfollowArtistsUsersOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["type"] == null) {
      throw new runtime.RequiredError(
        "type",
        'Required parameter "type" was null or undefined when calling unfollowArtistsUsers().',
      );
    }

    if (requestParameters["ids"] == null) {
      throw new runtime.RequiredError(
        "ids",
        'Required parameter "ids" was null or undefined when calling unfollowArtistsUsers().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["type"] != null) {
      queryParameters["type"] = requestParameters["type"];
    }

    if (requestParameters["ids"] != null) {
      queryParameters["ids"] = requestParameters["ids"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-follow-modify"],
      );
    }

    let urlPath = `/me/following`;

    const response = await this.request(
      {
        path: urlPath,
        method: "DELETE",
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters["unfollowArtistsUsersRequest"],
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Remove the current user as a follower of one or more artists or other Spotify users.
   * Unfollow Artists or Users
   */
  async unfollowArtistsUsers(
    requestParameters: ArtistsApiUnfollowArtistsUsersOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.unfollowArtistsUsersRaw(requestParameters, initOverrides);
  }
}
