/* tslint:disable */
/* eslint-disable */
/**
 * Spotify Web API with fixes and improvements from sonallux
 * You can use Spotify\'s Web API to discover music and podcasts, manage your Spotify library, control audio playback, and much more. Browse our available Web API endpoints using the sidebar at left, or via the navigation bar on top of this page on smaller screens.  In order to make successful Web API requests your app will need a valid access token. One can be obtained through <a href=\"https://developer.spotify.com/documentation/general/guides/authorization-guide/\">OAuth 2.0</a>.  The base URI for all Web API requests is `https://api.spotify.com/v1`.  Need help? See our <a href=\"https://developer.spotify.com/documentation/web-api/guides/\">Web API guides</a> for more information, or visit the <a href=\"https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer\">Spotify for Developers community forum</a> to ask questions and connect with other developers.
 *
 * The version of the OpenAPI document: 2025.5.18
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
  CategoryObject,
  InlineObject,
  InlineObject6,
  PagingFeaturedPlaylistObject,
} from "../models/index";
import * as runtime from "../runtime";

export interface CategoriesApiGetACategoriesPlaylistsRequest {
  categoryId: string;
  limit?: number;
  offset?: number;
}

export interface CategoriesApiGetACategoryRequest {
  categoryId: string;
  locale?: string;
}

export interface CategoriesApiGetCategoriesRequest {
  locale?: string;
  limit?: number;
  offset?: number;
}

/**
 *
 */
export class CategoriesApi extends runtime.BaseAPI {
  /**
   * Get a list of Spotify playlists tagged with a particular category.
   * Get Category\'s Playlists
   * @deprecated
   */
  async getACategoriesPlaylistsRaw(
    requestParameters: CategoriesApiGetACategoriesPlaylistsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PagingFeaturedPlaylistObject>> {
    if (requestParameters["categoryId"] == null) {
      throw new runtime.RequiredError(
        "categoryId",
        'Required parameter "categoryId" was null or undefined when calling getACategoriesPlaylists().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    if (requestParameters["offset"] != null) {
      queryParameters["offset"] = requestParameters["offset"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        [],
      );
    }

    let urlPath = `/browse/categories/{category_id}/playlists`;
    urlPath = urlPath.replace(
      `{${"category_id"}}`,
      encodeURIComponent(String(requestParameters["categoryId"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get a list of Spotify playlists tagged with a particular category.
   * Get Category\'s Playlists
   * @deprecated
   */
  async getACategoriesPlaylists(
    requestParameters: CategoriesApiGetACategoriesPlaylistsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PagingFeaturedPlaylistObject> {
    const response = await this.getACategoriesPlaylistsRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Get a single category used to tag items in Spotify (on, for example, the Spotify player’s “Browse” tab).
   * Get Single Browse Category
   */
  async getACategoryRaw(
    requestParameters: CategoriesApiGetACategoryRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<CategoryObject>> {
    if (requestParameters["categoryId"] == null) {
      throw new runtime.RequiredError(
        "categoryId",
        'Required parameter "categoryId" was null or undefined when calling getACategory().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["locale"] != null) {
      queryParameters["locale"] = requestParameters["locale"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        [],
      );
    }

    let urlPath = `/browse/categories/{category_id}`;
    urlPath = urlPath.replace(
      `{${"category_id"}}`,
      encodeURIComponent(String(requestParameters["categoryId"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get a single category used to tag items in Spotify (on, for example, the Spotify player’s “Browse” tab).
   * Get Single Browse Category
   */
  async getACategory(
    requestParameters: CategoriesApiGetACategoryRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<CategoryObject> {
    const response = await this.getACategoryRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Get a list of categories used to tag items in Spotify (on, for example, the Spotify player’s “Browse” tab).
   * Get Several Browse Categories
   */
  async getCategoriesRaw(
    requestParameters: CategoriesApiGetCategoriesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<InlineObject6>> {
    const queryParameters: any = {};

    if (requestParameters["locale"] != null) {
      queryParameters["locale"] = requestParameters["locale"];
    }

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    if (requestParameters["offset"] != null) {
      queryParameters["offset"] = requestParameters["offset"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        [],
      );
    }

    let urlPath = `/browse/categories`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get a list of categories used to tag items in Spotify (on, for example, the Spotify player’s “Browse” tab).
   * Get Several Browse Categories
   */
  async getCategories(
    requestParameters: CategoriesApiGetCategoriesRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<InlineObject6> {
    const response = await this.getCategoriesRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }
}
