/* tslint:disable */
/* eslint-disable */
/**
 * Spotify Web API with fixes and improvements from sonallux
 * You can use Spotify\'s Web API to discover music and podcasts, manage your Spotify library, control audio playback, and much more. Browse our available Web API endpoints using the sidebar at left, or via the navigation bar on top of this page on smaller screens.  In order to make successful Web API requests your app will need a valid access token. One can be obtained through <a href=\"https://developer.spotify.com/documentation/general/guides/authorization-guide/\">OAuth 2.0</a>.  The base URI for all Web API requests is `https://api.spotify.com/v1`.  Need help? See our <a href=\"https://developer.spotify.com/documentation/web-api/guides/\">Web API guides</a> for more information, or visit the <a href=\"https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer\">Spotify for Developers community forum</a> to ask questions and connect with other developers.
 *
 * The version of the OpenAPI document: 2025.5.18
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
  ChapterObject,
  GetAnAlbum401Response,
  GetSeveralChapters200Response,
  PagingSimplifiedChapterObject,
} from "../models/index";
import * as runtime from "../runtime";

export interface ChaptersApiGetAChapterRequest {
  id: string;
  market?: string;
}

export interface ChaptersApiGetAudiobookChaptersRequest {
  id: string;
  market?: string;
  limit?: number;
  offset?: number;
}

export interface ChaptersApiGetSeveralChaptersRequest {
  ids: string;
  market?: string;
}

/**
 *
 */
export class ChaptersApi extends runtime.BaseAPI {
  /**
   * Get Spotify catalog information for a single audiobook chapter. Chapters are only available within the US, UK, Canada, Ireland, New Zealand and Australia markets.
   * Get a Chapter
   */
  async getAChapterRaw(
    requestParameters: ChaptersApiGetAChapterRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ChapterObject>> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling getAChapter().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["market"] != null) {
      queryParameters["market"] = requestParameters["market"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        [],
      );
    }

    let urlPath = `/chapters/{id}`;
    urlPath = urlPath.replace(
      `{${"id"}}`,
      encodeURIComponent(String(requestParameters["id"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get Spotify catalog information for a single audiobook chapter. Chapters are only available within the US, UK, Canada, Ireland, New Zealand and Australia markets.
   * Get a Chapter
   */
  async getAChapter(
    requestParameters: ChaptersApiGetAChapterRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ChapterObject> {
    const response = await this.getAChapterRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Get Spotify catalog information about an audiobook\'s chapters. Audiobooks are only available within the US, UK, Canada, Ireland, New Zealand and Australia markets.
   * Get Audiobook Chapters
   */
  async getAudiobookChaptersRaw(
    requestParameters: ChaptersApiGetAudiobookChaptersRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PagingSimplifiedChapterObject>> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling getAudiobookChapters().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["market"] != null) {
      queryParameters["market"] = requestParameters["market"];
    }

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    if (requestParameters["offset"] != null) {
      queryParameters["offset"] = requestParameters["offset"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        [],
      );
    }

    let urlPath = `/audiobooks/{id}/chapters`;
    urlPath = urlPath.replace(
      `{${"id"}}`,
      encodeURIComponent(String(requestParameters["id"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get Spotify catalog information about an audiobook\'s chapters. Audiobooks are only available within the US, UK, Canada, Ireland, New Zealand and Australia markets.
   * Get Audiobook Chapters
   */
  async getAudiobookChapters(
    requestParameters: ChaptersApiGetAudiobookChaptersRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PagingSimplifiedChapterObject> {
    const response = await this.getAudiobookChaptersRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Get Spotify catalog information for several audiobook chapters identified by their Spotify IDs. Chapters are only available within the US, UK, Canada, Ireland, New Zealand and Australia markets.
   * Get Several Chapters
   */
  async getSeveralChaptersRaw(
    requestParameters: ChaptersApiGetSeveralChaptersRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<GetSeveralChapters200Response>> {
    if (requestParameters["ids"] == null) {
      throw new runtime.RequiredError(
        "ids",
        'Required parameter "ids" was null or undefined when calling getSeveralChapters().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["ids"] != null) {
      queryParameters["ids"] = requestParameters["ids"];
    }

    if (requestParameters["market"] != null) {
      queryParameters["market"] = requestParameters["market"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        [],
      );
    }

    let urlPath = `/chapters`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get Spotify catalog information for several audiobook chapters identified by their Spotify IDs. Chapters are only available within the US, UK, Canada, Ireland, New Zealand and Australia markets.
   * Get Several Chapters
   */
  async getSeveralChapters(
    requestParameters: ChaptersApiGetSeveralChaptersRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<GetSeveralChapters200Response> {
    const response = await this.getSeveralChaptersRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }
}
