/* tslint:disable */
/* eslint-disable */
/**
 * Spotify Web API with fixes and improvements from sonallux
 * You can use Spotify\'s Web API to discover music and podcasts, manage your Spotify library, control audio playback, and much more. Browse our available Web API endpoints using the sidebar at left, or via the navigation bar on top of this page on smaller screens.  In order to make successful Web API requests your app will need a valid access token. One can be obtained through <a href=\"https://developer.spotify.com/documentation/general/guides/authorization-guide/\">OAuth 2.0</a>.  The base URI for all Web API requests is `https://api.spotify.com/v1`.  Need help? See our <a href=\"https://developer.spotify.com/documentation/web-api/guides/\">Web API guides</a> for more information, or visit the <a href=\"https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer\">Spotify for Developers community forum</a> to ask questions and connect with other developers.
 *
 * The version of the OpenAPI document: 2025.5.18
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
  EpisodeObject,
  GetAnAlbum401Response,
  GetMultipleEpisodes200Response,
  PagingSavedEpisodeObject,
  PagingSimplifiedEpisodeObject,
  RemoveEpisodesUserRequest,
  SaveEpisodesUserRequest,
} from "../models/index";
import * as runtime from "../runtime";

export interface EpisodesApiCheckUsersSavedEpisodesRequest {
  ids: string;
}

export interface EpisodesApiGetAShowsEpisodesRequest {
  id: string;
  market?: string;
  limit?: number;
  offset?: number;
}

export interface EpisodesApiGetAnEpisodeRequest {
  id: string;
  market?: string;
}

export interface EpisodesApiGetMultipleEpisodesRequest {
  ids: string;
  market?: string;
}

export interface EpisodesApiGetUsersSavedEpisodesRequest {
  market?: string;
  limit?: number;
  offset?: number;
}

export interface EpisodesApiRemoveEpisodesUserOperationRequest {
  ids: string;
  removeEpisodesUserRequest?: RemoveEpisodesUserRequest;
}

export interface EpisodesApiSaveEpisodesUserOperationRequest {
  ids: string;
  saveEpisodesUserRequest?: SaveEpisodesUserRequest;
}

/**
 *
 */
export class EpisodesApi extends runtime.BaseAPI {
  /**
   * Check if one or more episodes is already saved in the current Spotify user\'s \'Your Episodes\' library.<br/> This API endpoint is in __beta__ and could change without warning. Please share any feedback that you have, or issues that you discover, in our [developer community forum](https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer)..
   * Check User\'s Saved Episodes
   */
  async checkUsersSavedEpisodesRaw(
    requestParameters: EpisodesApiCheckUsersSavedEpisodesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<boolean>>> {
    if (requestParameters["ids"] == null) {
      throw new runtime.RequiredError(
        "ids",
        'Required parameter "ids" was null or undefined when calling checkUsersSavedEpisodes().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["ids"] != null) {
      queryParameters["ids"] = requestParameters["ids"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-library-read"],
      );
    }

    let urlPath = `/me/episodes/contains`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse<any>(response);
  }

  /**
   * Check if one or more episodes is already saved in the current Spotify user\'s \'Your Episodes\' library.<br/> This API endpoint is in __beta__ and could change without warning. Please share any feedback that you have, or issues that you discover, in our [developer community forum](https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer)..
   * Check User\'s Saved Episodes
   */
  async checkUsersSavedEpisodes(
    requestParameters: EpisodesApiCheckUsersSavedEpisodesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<boolean>> {
    const response = await this.checkUsersSavedEpisodesRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Get Spotify catalog information about an show’s episodes. Optional parameters can be used to limit the number of episodes returned.
   * Get Show Episodes
   */
  async getAShowsEpisodesRaw(
    requestParameters: EpisodesApiGetAShowsEpisodesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PagingSimplifiedEpisodeObject>> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling getAShowsEpisodes().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["market"] != null) {
      queryParameters["market"] = requestParameters["market"];
    }

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    if (requestParameters["offset"] != null) {
      queryParameters["offset"] = requestParameters["offset"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-read-playback-position"],
      );
    }

    let urlPath = `/shows/{id}/episodes`;
    urlPath = urlPath.replace(
      `{${"id"}}`,
      encodeURIComponent(String(requestParameters["id"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get Spotify catalog information about an show’s episodes. Optional parameters can be used to limit the number of episodes returned.
   * Get Show Episodes
   */
  async getAShowsEpisodes(
    requestParameters: EpisodesApiGetAShowsEpisodesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PagingSimplifiedEpisodeObject> {
    const response = await this.getAShowsEpisodesRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Get Spotify catalog information for a single episode identified by its unique Spotify ID.
   * Get Episode
   */
  async getAnEpisodeRaw(
    requestParameters: EpisodesApiGetAnEpisodeRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<EpisodeObject>> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling getAnEpisode().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["market"] != null) {
      queryParameters["market"] = requestParameters["market"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-read-playback-position"],
      );
    }

    let urlPath = `/episodes/{id}`;
    urlPath = urlPath.replace(
      `{${"id"}}`,
      encodeURIComponent(String(requestParameters["id"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get Spotify catalog information for a single episode identified by its unique Spotify ID.
   * Get Episode
   */
  async getAnEpisode(
    requestParameters: EpisodesApiGetAnEpisodeRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<EpisodeObject> {
    const response = await this.getAnEpisodeRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Get Spotify catalog information for several episodes based on their Spotify IDs.
   * Get Several Episodes
   */
  async getMultipleEpisodesRaw(
    requestParameters: EpisodesApiGetMultipleEpisodesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<GetMultipleEpisodes200Response>> {
    if (requestParameters["ids"] == null) {
      throw new runtime.RequiredError(
        "ids",
        'Required parameter "ids" was null or undefined when calling getMultipleEpisodes().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["ids"] != null) {
      queryParameters["ids"] = requestParameters["ids"];
    }

    if (requestParameters["market"] != null) {
      queryParameters["market"] = requestParameters["market"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-read-playback-position"],
      );
    }

    let urlPath = `/episodes`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get Spotify catalog information for several episodes based on their Spotify IDs.
   * Get Several Episodes
   */
  async getMultipleEpisodes(
    requestParameters: EpisodesApiGetMultipleEpisodesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<GetMultipleEpisodes200Response> {
    const response = await this.getMultipleEpisodesRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Get a list of the episodes saved in the current Spotify user\'s library.<br/> This API endpoint is in __beta__ and could change without warning. Please share any feedback that you have, or issues that you discover, in our [developer community forum](https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer).
   * Get User\'s Saved Episodes
   */
  async getUsersSavedEpisodesRaw(
    requestParameters: EpisodesApiGetUsersSavedEpisodesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PagingSavedEpisodeObject>> {
    const queryParameters: any = {};

    if (requestParameters["market"] != null) {
      queryParameters["market"] = requestParameters["market"];
    }

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    if (requestParameters["offset"] != null) {
      queryParameters["offset"] = requestParameters["offset"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-library-read", "user-read-playback-position"],
      );
    }

    let urlPath = `/me/episodes`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get a list of the episodes saved in the current Spotify user\'s library.<br/> This API endpoint is in __beta__ and could change without warning. Please share any feedback that you have, or issues that you discover, in our [developer community forum](https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer).
   * Get User\'s Saved Episodes
   */
  async getUsersSavedEpisodes(
    requestParameters: EpisodesApiGetUsersSavedEpisodesRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PagingSavedEpisodeObject> {
    const response = await this.getUsersSavedEpisodesRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Remove one or more episodes from the current user\'s library.<br/> This API endpoint is in __beta__ and could change without warning. Please share any feedback that you have, or issues that you discover, in our [developer community forum](https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer).
   * Remove User\'s Saved Episodes
   */
  async removeEpisodesUserRaw(
    requestParameters: EpisodesApiRemoveEpisodesUserOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["ids"] == null) {
      throw new runtime.RequiredError(
        "ids",
        'Required parameter "ids" was null or undefined when calling removeEpisodesUser().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["ids"] != null) {
      queryParameters["ids"] = requestParameters["ids"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-library-modify"],
      );
    }

    let urlPath = `/me/episodes`;

    const response = await this.request(
      {
        path: urlPath,
        method: "DELETE",
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters["removeEpisodesUserRequest"],
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Remove one or more episodes from the current user\'s library.<br/> This API endpoint is in __beta__ and could change without warning. Please share any feedback that you have, or issues that you discover, in our [developer community forum](https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer).
   * Remove User\'s Saved Episodes
   */
  async removeEpisodesUser(
    requestParameters: EpisodesApiRemoveEpisodesUserOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.removeEpisodesUserRaw(requestParameters, initOverrides);
  }

  /**
   * Save one or more episodes to the current user\'s library.<br/> This API endpoint is in __beta__ and could change without warning. Please share any feedback that you have, or issues that you discover, in our [developer community forum](https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer).
   * Save Episodes for Current User
   */
  async saveEpisodesUserRaw(
    requestParameters: EpisodesApiSaveEpisodesUserOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["ids"] == null) {
      throw new runtime.RequiredError(
        "ids",
        'Required parameter "ids" was null or undefined when calling saveEpisodesUser().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["ids"] != null) {
      queryParameters["ids"] = requestParameters["ids"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-library-modify"],
      );
    }

    let urlPath = `/me/episodes`;

    const response = await this.request(
      {
        path: urlPath,
        method: "PUT",
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters["saveEpisodesUserRequest"],
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Save one or more episodes to the current user\'s library.<br/> This API endpoint is in __beta__ and could change without warning. Please share any feedback that you have, or issues that you discover, in our [developer community forum](https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer).
   * Save Episodes for Current User
   */
  async saveEpisodesUser(
    requestParameters: EpisodesApiSaveEpisodesUserOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.saveEpisodesUserRaw(requestParameters, initOverrides);
  }
}
