/* tslint:disable */
/* eslint-disable */
/**
 * Spotify Web API with fixes and improvements from sonallux
 * You can use Spotify\'s Web API to discover music and podcasts, manage your Spotify library, control audio playback, and much more. Browse our available Web API endpoints using the sidebar at left, or via the navigation bar on top of this page on smaller screens.  In order to make successful Web API requests your app will need a valid access token. One can be obtained through <a href=\"https://developer.spotify.com/documentation/general/guides/authorization-guide/\">OAuth 2.0</a>.  The base URI for all Web API requests is `https://api.spotify.com/v1`.  Need help? See our <a href=\"https://developer.spotify.com/documentation/web-api/guides/\">Web API guides</a> for more information, or visit the <a href=\"https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer\">Spotify for Developers community forum</a> to ask questions and connect with other developers.
 *
 * The version of the OpenAPI document: 2025.5.18
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
  ChangePlaylistDetailsRequest,
  CreatePlaylistRequest,
  FollowArtistsUsersRequest,
  InlineObject,
  InlineObject7,
  PagingArtistObject,
  PagingPlaylistObject,
  PagingSavedAlbumObject,
  PagingSavedAudiobookObject,
  PagingSavedEpisodeObject,
  PagingSavedShowObject,
  PagingSavedTrackObject,
  PagingTrackObject,
  PlaylistObject,
  RemoveEpisodesUserRequest,
  SaveAlbumsUserRequest,
  SaveEpisodesUserRequest,
  SaveShowsUserRequest,
  SaveTracksUserRequest,
  UnfollowArtistsUsersRequest,
} from "../models/index";
import * as runtime from "../runtime";

export interface LibraryApiChangePlaylistDetailsOperationRequest {
  playlistId: string;
  changePlaylistDetailsRequest?: ChangePlaylistDetailsRequest;
}

export interface LibraryApiCheckCurrentUserFollowsRequest {
  type: CheckCurrentUserFollowsTypeEnum;
  ids: string;
}

export interface LibraryApiCheckUsersSavedAlbumsRequest {
  ids: string;
}

export interface LibraryApiCheckUsersSavedAudiobooksRequest {
  ids: string;
}

export interface LibraryApiCheckUsersSavedEpisodesRequest {
  ids: string;
}

export interface LibraryApiCheckUsersSavedShowsRequest {
  ids: string;
}

export interface LibraryApiCheckUsersSavedTracksRequest {
  ids: string;
}

export interface LibraryApiCreatePlaylistOperationRequest {
  userId: string;
  createPlaylistRequest?: CreatePlaylistRequest;
}

export interface LibraryApiFollowArtistsUsersOperationRequest {
  type: FollowArtistsUsersOperationTypeEnum;
  ids: string;
  followArtistsUsersRequest?: FollowArtistsUsersRequest;
}

export interface LibraryApiGetAListOfCurrentUsersPlaylistsRequest {
  limit?: number;
  offset?: number;
}

export interface LibraryApiGetFollowedRequest {
  type: GetFollowedTypeEnum;
  after?: string;
  limit?: number;
}

export interface LibraryApiGetUsersSavedAlbumsRequest {
  limit?: number;
  offset?: number;
  market?: string;
}

export interface LibraryApiGetUsersSavedAudiobooksRequest {
  limit?: number;
  offset?: number;
}

export interface LibraryApiGetUsersSavedEpisodesRequest {
  market?: string;
  limit?: number;
  offset?: number;
}

export interface LibraryApiGetUsersSavedShowsRequest {
  limit?: number;
  offset?: number;
}

export interface LibraryApiGetUsersSavedTracksRequest {
  market?: string;
  limit?: number;
  offset?: number;
}

export interface LibraryApiGetUsersTopArtistsRequest {
  timeRange?: string;
  limit?: number;
  offset?: number;
}

export interface LibraryApiGetUsersTopTracksRequest {
  timeRange?: string;
  limit?: number;
  offset?: number;
}

export interface LibraryApiRemoveAlbumsUserRequest {
  ids: string;
  saveAlbumsUserRequest?: SaveAlbumsUserRequest;
}

export interface LibraryApiRemoveAudiobooksUserRequest {
  ids: string;
}

export interface LibraryApiRemoveEpisodesUserOperationRequest {
  ids: string;
  removeEpisodesUserRequest?: RemoveEpisodesUserRequest;
}

export interface LibraryApiRemoveShowsUserRequest {
  ids: string;
  market?: string;
  saveShowsUserRequest?: SaveShowsUserRequest;
}

export interface LibraryApiRemoveTracksUserRequest {
  ids: string;
  saveAlbumsUserRequest?: SaveAlbumsUserRequest;
}

export interface LibraryApiSaveAlbumsUserOperationRequest {
  ids: string;
  saveAlbumsUserRequest?: SaveAlbumsUserRequest;
}

export interface LibraryApiSaveAudiobooksUserRequest {
  ids: string;
}

export interface LibraryApiSaveEpisodesUserOperationRequest {
  ids: string;
  saveEpisodesUserRequest?: SaveEpisodesUserRequest;
}

export interface LibraryApiSaveShowsUserOperationRequest {
  ids: string;
  saveShowsUserRequest?: SaveShowsUserRequest;
}

export interface LibraryApiSaveTracksUserOperationRequest {
  ids: string;
  saveTracksUserRequest?: SaveTracksUserRequest;
}

export interface LibraryApiUnfollowArtistsUsersOperationRequest {
  type: UnfollowArtistsUsersOperationTypeEnum;
  ids: string;
  unfollowArtistsUsersRequest?: UnfollowArtistsUsersRequest;
}

/**
 *
 */
export class LibraryApi extends runtime.BaseAPI {
  /**
   * Change a playlist\'s name and public/private state. (The user must, of course, own the playlist.)
   * Change Playlist Details
   */
  async changePlaylistDetailsRaw(
    requestParameters: LibraryApiChangePlaylistDetailsOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["playlistId"] == null) {
      throw new runtime.RequiredError(
        "playlistId",
        'Required parameter "playlistId" was null or undefined when calling changePlaylistDetails().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["playlist-modify-public", "playlist-modify-private"],
      );
    }

    let urlPath = `/playlists/{playlist_id}`;
    urlPath = urlPath.replace(
      `{${"playlist_id"}}`,
      encodeURIComponent(String(requestParameters["playlistId"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "PUT",
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters["changePlaylistDetailsRequest"],
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Change a playlist\'s name and public/private state. (The user must, of course, own the playlist.)
   * Change Playlist Details
   */
  async changePlaylistDetails(
    requestParameters: LibraryApiChangePlaylistDetailsOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.changePlaylistDetailsRaw(requestParameters, initOverrides);
  }

  /**
   * Check to see if the current user is following one or more artists or other Spotify users.
   * Check If User Follows Artists or Users
   */
  async checkCurrentUserFollowsRaw(
    requestParameters: LibraryApiCheckCurrentUserFollowsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<boolean>>> {
    if (requestParameters["type"] == null) {
      throw new runtime.RequiredError(
        "type",
        'Required parameter "type" was null or undefined when calling checkCurrentUserFollows().',
      );
    }

    if (requestParameters["ids"] == null) {
      throw new runtime.RequiredError(
        "ids",
        'Required parameter "ids" was null or undefined when calling checkCurrentUserFollows().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["type"] != null) {
      queryParameters["type"] = requestParameters["type"];
    }

    if (requestParameters["ids"] != null) {
      queryParameters["ids"] = requestParameters["ids"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-follow-read"],
      );
    }

    let urlPath = `/me/following/contains`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse<any>(response);
  }

  /**
   * Check to see if the current user is following one or more artists or other Spotify users.
   * Check If User Follows Artists or Users
   */
  async checkCurrentUserFollows(
    requestParameters: LibraryApiCheckCurrentUserFollowsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<boolean>> {
    const response = await this.checkCurrentUserFollowsRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Check if one or more albums is already saved in the current Spotify user\'s \'Your Music\' library.
   * Check User\'s Saved Albums
   */
  async checkUsersSavedAlbumsRaw(
    requestParameters: LibraryApiCheckUsersSavedAlbumsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<boolean>>> {
    if (requestParameters["ids"] == null) {
      throw new runtime.RequiredError(
        "ids",
        'Required parameter "ids" was null or undefined when calling checkUsersSavedAlbums().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["ids"] != null) {
      queryParameters["ids"] = requestParameters["ids"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-library-read"],
      );
    }

    let urlPath = `/me/albums/contains`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse<any>(response);
  }

  /**
   * Check if one or more albums is already saved in the current Spotify user\'s \'Your Music\' library.
   * Check User\'s Saved Albums
   */
  async checkUsersSavedAlbums(
    requestParameters: LibraryApiCheckUsersSavedAlbumsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<boolean>> {
    const response = await this.checkUsersSavedAlbumsRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Check if one or more audiobooks are already saved in the current Spotify user\'s library.
   * Check User\'s Saved Audiobooks
   */
  async checkUsersSavedAudiobooksRaw(
    requestParameters: LibraryApiCheckUsersSavedAudiobooksRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<boolean>>> {
    if (requestParameters["ids"] == null) {
      throw new runtime.RequiredError(
        "ids",
        'Required parameter "ids" was null or undefined when calling checkUsersSavedAudiobooks().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["ids"] != null) {
      queryParameters["ids"] = requestParameters["ids"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-library-read"],
      );
    }

    let urlPath = `/me/audiobooks/contains`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse<any>(response);
  }

  /**
   * Check if one or more audiobooks are already saved in the current Spotify user\'s library.
   * Check User\'s Saved Audiobooks
   */
  async checkUsersSavedAudiobooks(
    requestParameters: LibraryApiCheckUsersSavedAudiobooksRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<boolean>> {
    const response = await this.checkUsersSavedAudiobooksRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Check if one or more episodes is already saved in the current Spotify user\'s \'Your Episodes\' library.<br/> This API endpoint is in __beta__ and could change without warning. Please share any feedback that you have, or issues that you discover, in our [developer community forum](https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer)..
   * Check User\'s Saved Episodes
   */
  async checkUsersSavedEpisodesRaw(
    requestParameters: LibraryApiCheckUsersSavedEpisodesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<boolean>>> {
    if (requestParameters["ids"] == null) {
      throw new runtime.RequiredError(
        "ids",
        'Required parameter "ids" was null or undefined when calling checkUsersSavedEpisodes().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["ids"] != null) {
      queryParameters["ids"] = requestParameters["ids"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-library-read"],
      );
    }

    let urlPath = `/me/episodes/contains`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse<any>(response);
  }

  /**
   * Check if one or more episodes is already saved in the current Spotify user\'s \'Your Episodes\' library.<br/> This API endpoint is in __beta__ and could change without warning. Please share any feedback that you have, or issues that you discover, in our [developer community forum](https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer)..
   * Check User\'s Saved Episodes
   */
  async checkUsersSavedEpisodes(
    requestParameters: LibraryApiCheckUsersSavedEpisodesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<boolean>> {
    const response = await this.checkUsersSavedEpisodesRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Check if one or more shows is already saved in the current Spotify user\'s library.
   * Check User\'s Saved Shows
   */
  async checkUsersSavedShowsRaw(
    requestParameters: LibraryApiCheckUsersSavedShowsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<boolean>>> {
    if (requestParameters["ids"] == null) {
      throw new runtime.RequiredError(
        "ids",
        'Required parameter "ids" was null or undefined when calling checkUsersSavedShows().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["ids"] != null) {
      queryParameters["ids"] = requestParameters["ids"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-library-read"],
      );
    }

    let urlPath = `/me/shows/contains`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse<any>(response);
  }

  /**
   * Check if one or more shows is already saved in the current Spotify user\'s library.
   * Check User\'s Saved Shows
   */
  async checkUsersSavedShows(
    requestParameters: LibraryApiCheckUsersSavedShowsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<boolean>> {
    const response = await this.checkUsersSavedShowsRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Check if one or more tracks is already saved in the current Spotify user\'s \'Your Music\' library.
   * Check User\'s Saved Tracks
   */
  async checkUsersSavedTracksRaw(
    requestParameters: LibraryApiCheckUsersSavedTracksRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<boolean>>> {
    if (requestParameters["ids"] == null) {
      throw new runtime.RequiredError(
        "ids",
        'Required parameter "ids" was null or undefined when calling checkUsersSavedTracks().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["ids"] != null) {
      queryParameters["ids"] = requestParameters["ids"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-library-read"],
      );
    }

    let urlPath = `/me/tracks/contains`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse<any>(response);
  }

  /**
   * Check if one or more tracks is already saved in the current Spotify user\'s \'Your Music\' library.
   * Check User\'s Saved Tracks
   */
  async checkUsersSavedTracks(
    requestParameters: LibraryApiCheckUsersSavedTracksRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<boolean>> {
    const response = await this.checkUsersSavedTracksRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Create a playlist for a Spotify user. (The playlist will be empty until you [add tracks](/documentation/web-api/reference/add-tracks-to-playlist).) Each user is generally limited to a maximum of 11000 playlists.
   * Create Playlist
   */
  async createPlaylistRaw(
    requestParameters: LibraryApiCreatePlaylistOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PlaylistObject>> {
    if (requestParameters["userId"] == null) {
      throw new runtime.RequiredError(
        "userId",
        'Required parameter "userId" was null or undefined when calling createPlaylist().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["playlist-modify-public", "playlist-modify-private"],
      );
    }

    let urlPath = `/users/{user_id}/playlists`;
    urlPath = urlPath.replace(
      `{${"user_id"}}`,
      encodeURIComponent(String(requestParameters["userId"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters["createPlaylistRequest"],
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Create a playlist for a Spotify user. (The playlist will be empty until you [add tracks](/documentation/web-api/reference/add-tracks-to-playlist).) Each user is generally limited to a maximum of 11000 playlists.
   * Create Playlist
   */
  async createPlaylist(
    requestParameters: LibraryApiCreatePlaylistOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PlaylistObject> {
    const response = await this.createPlaylistRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Add the current user as a follower of one or more artists or other Spotify users.
   * Follow Artists or Users
   */
  async followArtistsUsersRaw(
    requestParameters: LibraryApiFollowArtistsUsersOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["type"] == null) {
      throw new runtime.RequiredError(
        "type",
        'Required parameter "type" was null or undefined when calling followArtistsUsers().',
      );
    }

    if (requestParameters["ids"] == null) {
      throw new runtime.RequiredError(
        "ids",
        'Required parameter "ids" was null or undefined when calling followArtistsUsers().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["type"] != null) {
      queryParameters["type"] = requestParameters["type"];
    }

    if (requestParameters["ids"] != null) {
      queryParameters["ids"] = requestParameters["ids"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-follow-modify"],
      );
    }

    let urlPath = `/me/following`;

    const response = await this.request(
      {
        path: urlPath,
        method: "PUT",
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters["followArtistsUsersRequest"],
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Add the current user as a follower of one or more artists or other Spotify users.
   * Follow Artists or Users
   */
  async followArtistsUsers(
    requestParameters: LibraryApiFollowArtistsUsersOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.followArtistsUsersRaw(requestParameters, initOverrides);
  }

  /**
   * Get a list of the playlists owned or followed by the current Spotify user.
   * Get Current User\'s Playlists
   */
  async getAListOfCurrentUsersPlaylistsRaw(
    requestParameters: LibraryApiGetAListOfCurrentUsersPlaylistsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PagingPlaylistObject>> {
    const queryParameters: any = {};

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    if (requestParameters["offset"] != null) {
      queryParameters["offset"] = requestParameters["offset"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["playlist-read-private"],
      );
    }

    let urlPath = `/me/playlists`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get a list of the playlists owned or followed by the current Spotify user.
   * Get Current User\'s Playlists
   */
  async getAListOfCurrentUsersPlaylists(
    requestParameters: LibraryApiGetAListOfCurrentUsersPlaylistsRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PagingPlaylistObject> {
    const response = await this.getAListOfCurrentUsersPlaylistsRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Get the current user\'s followed artists.
   * Get Followed Artists
   */
  async getFollowedRaw(
    requestParameters: LibraryApiGetFollowedRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<InlineObject7>> {
    if (requestParameters["type"] == null) {
      throw new runtime.RequiredError(
        "type",
        'Required parameter "type" was null or undefined when calling getFollowed().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["type"] != null) {
      queryParameters["type"] = requestParameters["type"];
    }

    if (requestParameters["after"] != null) {
      queryParameters["after"] = requestParameters["after"];
    }

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-follow-read"],
      );
    }

    let urlPath = `/me/following`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get the current user\'s followed artists.
   * Get Followed Artists
   */
  async getFollowed(
    requestParameters: LibraryApiGetFollowedRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<InlineObject7> {
    const response = await this.getFollowedRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Get a list of the albums saved in the current Spotify user\'s \'Your Music\' library.
   * Get User\'s Saved Albums
   */
  async getUsersSavedAlbumsRaw(
    requestParameters: LibraryApiGetUsersSavedAlbumsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PagingSavedAlbumObject>> {
    const queryParameters: any = {};

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    if (requestParameters["offset"] != null) {
      queryParameters["offset"] = requestParameters["offset"];
    }

    if (requestParameters["market"] != null) {
      queryParameters["market"] = requestParameters["market"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-library-read"],
      );
    }

    let urlPath = `/me/albums`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get a list of the albums saved in the current Spotify user\'s \'Your Music\' library.
   * Get User\'s Saved Albums
   */
  async getUsersSavedAlbums(
    requestParameters: LibraryApiGetUsersSavedAlbumsRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PagingSavedAlbumObject> {
    const response = await this.getUsersSavedAlbumsRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Get a list of the audiobooks saved in the current Spotify user\'s \'Your Music\' library.
   * Get User\'s Saved Audiobooks
   */
  async getUsersSavedAudiobooksRaw(
    requestParameters: LibraryApiGetUsersSavedAudiobooksRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PagingSavedAudiobookObject>> {
    const queryParameters: any = {};

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    if (requestParameters["offset"] != null) {
      queryParameters["offset"] = requestParameters["offset"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-library-read"],
      );
    }

    let urlPath = `/me/audiobooks`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get a list of the audiobooks saved in the current Spotify user\'s \'Your Music\' library.
   * Get User\'s Saved Audiobooks
   */
  async getUsersSavedAudiobooks(
    requestParameters: LibraryApiGetUsersSavedAudiobooksRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PagingSavedAudiobookObject> {
    const response = await this.getUsersSavedAudiobooksRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Get a list of the episodes saved in the current Spotify user\'s library.<br/> This API endpoint is in __beta__ and could change without warning. Please share any feedback that you have, or issues that you discover, in our [developer community forum](https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer).
   * Get User\'s Saved Episodes
   */
  async getUsersSavedEpisodesRaw(
    requestParameters: LibraryApiGetUsersSavedEpisodesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PagingSavedEpisodeObject>> {
    const queryParameters: any = {};

    if (requestParameters["market"] != null) {
      queryParameters["market"] = requestParameters["market"];
    }

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    if (requestParameters["offset"] != null) {
      queryParameters["offset"] = requestParameters["offset"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-library-read", "user-read-playback-position"],
      );
    }

    let urlPath = `/me/episodes`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get a list of the episodes saved in the current Spotify user\'s library.<br/> This API endpoint is in __beta__ and could change without warning. Please share any feedback that you have, or issues that you discover, in our [developer community forum](https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer).
   * Get User\'s Saved Episodes
   */
  async getUsersSavedEpisodes(
    requestParameters: LibraryApiGetUsersSavedEpisodesRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PagingSavedEpisodeObject> {
    const response = await this.getUsersSavedEpisodesRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Get a list of shows saved in the current Spotify user\'s library. Optional parameters can be used to limit the number of shows returned.
   * Get User\'s Saved Shows
   */
  async getUsersSavedShowsRaw(
    requestParameters: LibraryApiGetUsersSavedShowsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PagingSavedShowObject>> {
    const queryParameters: any = {};

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    if (requestParameters["offset"] != null) {
      queryParameters["offset"] = requestParameters["offset"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-library-read"],
      );
    }

    let urlPath = `/me/shows`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get a list of shows saved in the current Spotify user\'s library. Optional parameters can be used to limit the number of shows returned.
   * Get User\'s Saved Shows
   */
  async getUsersSavedShows(
    requestParameters: LibraryApiGetUsersSavedShowsRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PagingSavedShowObject> {
    const response = await this.getUsersSavedShowsRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Get a list of the songs saved in the current Spotify user\'s \'Your Music\' library.
   * Get User\'s Saved Tracks
   */
  async getUsersSavedTracksRaw(
    requestParameters: LibraryApiGetUsersSavedTracksRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PagingSavedTrackObject>> {
    const queryParameters: any = {};

    if (requestParameters["market"] != null) {
      queryParameters["market"] = requestParameters["market"];
    }

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    if (requestParameters["offset"] != null) {
      queryParameters["offset"] = requestParameters["offset"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-library-read"],
      );
    }

    let urlPath = `/me/tracks`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get a list of the songs saved in the current Spotify user\'s \'Your Music\' library.
   * Get User\'s Saved Tracks
   */
  async getUsersSavedTracks(
    requestParameters: LibraryApiGetUsersSavedTracksRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PagingSavedTrackObject> {
    const response = await this.getUsersSavedTracksRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Get the current user\'s top artists based on calculated affinity.
   * Get User\'s Top Artists
   */
  async getUsersTopArtistsRaw(
    requestParameters: LibraryApiGetUsersTopArtistsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PagingArtistObject>> {
    const queryParameters: any = {};

    if (requestParameters["timeRange"] != null) {
      queryParameters["time_range"] = requestParameters["timeRange"];
    }

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    if (requestParameters["offset"] != null) {
      queryParameters["offset"] = requestParameters["offset"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-top-read"],
      );
    }

    let urlPath = `/me/top/artists`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get the current user\'s top artists based on calculated affinity.
   * Get User\'s Top Artists
   */
  async getUsersTopArtists(
    requestParameters: LibraryApiGetUsersTopArtistsRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PagingArtistObject> {
    const response = await this.getUsersTopArtistsRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Get the current user\'s top tracks based on calculated affinity.
   * Get User\'s Top Tracks
   */
  async getUsersTopTracksRaw(
    requestParameters: LibraryApiGetUsersTopTracksRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PagingTrackObject>> {
    const queryParameters: any = {};

    if (requestParameters["timeRange"] != null) {
      queryParameters["time_range"] = requestParameters["timeRange"];
    }

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    if (requestParameters["offset"] != null) {
      queryParameters["offset"] = requestParameters["offset"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-top-read"],
      );
    }

    let urlPath = `/me/top/tracks`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get the current user\'s top tracks based on calculated affinity.
   * Get User\'s Top Tracks
   */
  async getUsersTopTracks(
    requestParameters: LibraryApiGetUsersTopTracksRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PagingTrackObject> {
    const response = await this.getUsersTopTracksRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Remove one or more albums from the current user\'s \'Your Music\' library.
   * Remove Users\' Saved Albums
   */
  async removeAlbumsUserRaw(
    requestParameters: LibraryApiRemoveAlbumsUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["ids"] == null) {
      throw new runtime.RequiredError(
        "ids",
        'Required parameter "ids" was null or undefined when calling removeAlbumsUser().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["ids"] != null) {
      queryParameters["ids"] = requestParameters["ids"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-library-modify"],
      );
    }

    let urlPath = `/me/albums`;

    const response = await this.request(
      {
        path: urlPath,
        method: "DELETE",
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters["saveAlbumsUserRequest"],
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Remove one or more albums from the current user\'s \'Your Music\' library.
   * Remove Users\' Saved Albums
   */
  async removeAlbumsUser(
    requestParameters: LibraryApiRemoveAlbumsUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.removeAlbumsUserRaw(requestParameters, initOverrides);
  }

  /**
   * Remove one or more audiobooks from the Spotify user\'s library.
   * Remove User\'s Saved Audiobooks
   */
  async removeAudiobooksUserRaw(
    requestParameters: LibraryApiRemoveAudiobooksUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["ids"] == null) {
      throw new runtime.RequiredError(
        "ids",
        'Required parameter "ids" was null or undefined when calling removeAudiobooksUser().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["ids"] != null) {
      queryParameters["ids"] = requestParameters["ids"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-library-modify"],
      );
    }

    let urlPath = `/me/audiobooks`;

    const response = await this.request(
      {
        path: urlPath,
        method: "DELETE",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Remove one or more audiobooks from the Spotify user\'s library.
   * Remove User\'s Saved Audiobooks
   */
  async removeAudiobooksUser(
    requestParameters: LibraryApiRemoveAudiobooksUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.removeAudiobooksUserRaw(requestParameters, initOverrides);
  }

  /**
   * Remove one or more episodes from the current user\'s library.<br/> This API endpoint is in __beta__ and could change without warning. Please share any feedback that you have, or issues that you discover, in our [developer community forum](https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer).
   * Remove User\'s Saved Episodes
   */
  async removeEpisodesUserRaw(
    requestParameters: LibraryApiRemoveEpisodesUserOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["ids"] == null) {
      throw new runtime.RequiredError(
        "ids",
        'Required parameter "ids" was null or undefined when calling removeEpisodesUser().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["ids"] != null) {
      queryParameters["ids"] = requestParameters["ids"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-library-modify"],
      );
    }

    let urlPath = `/me/episodes`;

    const response = await this.request(
      {
        path: urlPath,
        method: "DELETE",
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters["removeEpisodesUserRequest"],
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Remove one or more episodes from the current user\'s library.<br/> This API endpoint is in __beta__ and could change without warning. Please share any feedback that you have, or issues that you discover, in our [developer community forum](https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer).
   * Remove User\'s Saved Episodes
   */
  async removeEpisodesUser(
    requestParameters: LibraryApiRemoveEpisodesUserOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.removeEpisodesUserRaw(requestParameters, initOverrides);
  }

  /**
   * Delete one or more shows from current Spotify user\'s library.
   * Remove User\'s Saved Shows
   */
  async removeShowsUserRaw(
    requestParameters: LibraryApiRemoveShowsUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["ids"] == null) {
      throw new runtime.RequiredError(
        "ids",
        'Required parameter "ids" was null or undefined when calling removeShowsUser().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["ids"] != null) {
      queryParameters["ids"] = requestParameters["ids"];
    }

    if (requestParameters["market"] != null) {
      queryParameters["market"] = requestParameters["market"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-library-modify"],
      );
    }

    let urlPath = `/me/shows`;

    const response = await this.request(
      {
        path: urlPath,
        method: "DELETE",
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters["saveShowsUserRequest"],
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Delete one or more shows from current Spotify user\'s library.
   * Remove User\'s Saved Shows
   */
  async removeShowsUser(
    requestParameters: LibraryApiRemoveShowsUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.removeShowsUserRaw(requestParameters, initOverrides);
  }

  /**
   * Remove one or more tracks from the current user\'s \'Your Music\' library.
   * Remove User\'s Saved Tracks
   */
  async removeTracksUserRaw(
    requestParameters: LibraryApiRemoveTracksUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["ids"] == null) {
      throw new runtime.RequiredError(
        "ids",
        'Required parameter "ids" was null or undefined when calling removeTracksUser().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["ids"] != null) {
      queryParameters["ids"] = requestParameters["ids"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-library-modify"],
      );
    }

    let urlPath = `/me/tracks`;

    const response = await this.request(
      {
        path: urlPath,
        method: "DELETE",
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters["saveAlbumsUserRequest"],
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Remove one or more tracks from the current user\'s \'Your Music\' library.
   * Remove User\'s Saved Tracks
   */
  async removeTracksUser(
    requestParameters: LibraryApiRemoveTracksUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.removeTracksUserRaw(requestParameters, initOverrides);
  }

  /**
   * Save one or more albums to the current user\'s \'Your Music\' library.
   * Save Albums for Current User
   */
  async saveAlbumsUserRaw(
    requestParameters: LibraryApiSaveAlbumsUserOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["ids"] == null) {
      throw new runtime.RequiredError(
        "ids",
        'Required parameter "ids" was null or undefined when calling saveAlbumsUser().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["ids"] != null) {
      queryParameters["ids"] = requestParameters["ids"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-library-modify"],
      );
    }

    let urlPath = `/me/albums`;

    const response = await this.request(
      {
        path: urlPath,
        method: "PUT",
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters["saveAlbumsUserRequest"],
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Save one or more albums to the current user\'s \'Your Music\' library.
   * Save Albums for Current User
   */
  async saveAlbumsUser(
    requestParameters: LibraryApiSaveAlbumsUserOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.saveAlbumsUserRaw(requestParameters, initOverrides);
  }

  /**
   * Save one or more audiobooks to the current Spotify user\'s library.
   * Save Audiobooks for Current User
   */
  async saveAudiobooksUserRaw(
    requestParameters: LibraryApiSaveAudiobooksUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["ids"] == null) {
      throw new runtime.RequiredError(
        "ids",
        'Required parameter "ids" was null or undefined when calling saveAudiobooksUser().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["ids"] != null) {
      queryParameters["ids"] = requestParameters["ids"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-library-modify"],
      );
    }

    let urlPath = `/me/audiobooks`;

    const response = await this.request(
      {
        path: urlPath,
        method: "PUT",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Save one or more audiobooks to the current Spotify user\'s library.
   * Save Audiobooks for Current User
   */
  async saveAudiobooksUser(
    requestParameters: LibraryApiSaveAudiobooksUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.saveAudiobooksUserRaw(requestParameters, initOverrides);
  }

  /**
   * Save one or more episodes to the current user\'s library.<br/> This API endpoint is in __beta__ and could change without warning. Please share any feedback that you have, or issues that you discover, in our [developer community forum](https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer).
   * Save Episodes for Current User
   */
  async saveEpisodesUserRaw(
    requestParameters: LibraryApiSaveEpisodesUserOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["ids"] == null) {
      throw new runtime.RequiredError(
        "ids",
        'Required parameter "ids" was null or undefined when calling saveEpisodesUser().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["ids"] != null) {
      queryParameters["ids"] = requestParameters["ids"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-library-modify"],
      );
    }

    let urlPath = `/me/episodes`;

    const response = await this.request(
      {
        path: urlPath,
        method: "PUT",
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters["saveEpisodesUserRequest"],
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Save one or more episodes to the current user\'s library.<br/> This API endpoint is in __beta__ and could change without warning. Please share any feedback that you have, or issues that you discover, in our [developer community forum](https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer).
   * Save Episodes for Current User
   */
  async saveEpisodesUser(
    requestParameters: LibraryApiSaveEpisodesUserOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.saveEpisodesUserRaw(requestParameters, initOverrides);
  }

  /**
   * Save one or more shows to current Spotify user\'s library.
   * Save Shows for Current User
   */
  async saveShowsUserRaw(
    requestParameters: LibraryApiSaveShowsUserOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["ids"] == null) {
      throw new runtime.RequiredError(
        "ids",
        'Required parameter "ids" was null or undefined when calling saveShowsUser().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["ids"] != null) {
      queryParameters["ids"] = requestParameters["ids"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-library-modify"],
      );
    }

    let urlPath = `/me/shows`;

    const response = await this.request(
      {
        path: urlPath,
        method: "PUT",
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters["saveShowsUserRequest"],
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Save one or more shows to current Spotify user\'s library.
   * Save Shows for Current User
   */
  async saveShowsUser(
    requestParameters: LibraryApiSaveShowsUserOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.saveShowsUserRaw(requestParameters, initOverrides);
  }

  /**
   * Save one or more tracks to the current user\'s \'Your Music\' library.
   * Save Tracks for Current User
   */
  async saveTracksUserRaw(
    requestParameters: LibraryApiSaveTracksUserOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["ids"] == null) {
      throw new runtime.RequiredError(
        "ids",
        'Required parameter "ids" was null or undefined when calling saveTracksUser().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["ids"] != null) {
      queryParameters["ids"] = requestParameters["ids"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-library-modify"],
      );
    }

    let urlPath = `/me/tracks`;

    const response = await this.request(
      {
        path: urlPath,
        method: "PUT",
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters["saveTracksUserRequest"],
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Save one or more tracks to the current user\'s \'Your Music\' library.
   * Save Tracks for Current User
   */
  async saveTracksUser(
    requestParameters: LibraryApiSaveTracksUserOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.saveTracksUserRaw(requestParameters, initOverrides);
  }

  /**
   * Remove the current user as a follower of one or more artists or other Spotify users.
   * Unfollow Artists or Users
   */
  async unfollowArtistsUsersRaw(
    requestParameters: LibraryApiUnfollowArtistsUsersOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["type"] == null) {
      throw new runtime.RequiredError(
        "type",
        'Required parameter "type" was null or undefined when calling unfollowArtistsUsers().',
      );
    }

    if (requestParameters["ids"] == null) {
      throw new runtime.RequiredError(
        "ids",
        'Required parameter "ids" was null or undefined when calling unfollowArtistsUsers().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["type"] != null) {
      queryParameters["type"] = requestParameters["type"];
    }

    if (requestParameters["ids"] != null) {
      queryParameters["ids"] = requestParameters["ids"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-follow-modify"],
      );
    }

    let urlPath = `/me/following`;

    const response = await this.request(
      {
        path: urlPath,
        method: "DELETE",
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters["unfollowArtistsUsersRequest"],
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Remove the current user as a follower of one or more artists or other Spotify users.
   * Unfollow Artists or Users
   */
  async unfollowArtistsUsers(
    requestParameters: LibraryApiUnfollowArtistsUsersOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.unfollowArtistsUsersRaw(requestParameters, initOverrides);
  }
}

/**
 * @export
 */
export const CheckCurrentUserFollowsTypeEnum = {
  Artist: "artist",
  User: "user",
} as const;
export type CheckCurrentUserFollowsTypeEnum =
  (typeof CheckCurrentUserFollowsTypeEnum)[keyof typeof CheckCurrentUserFollowsTypeEnum];
/**
 * @export
 */
export const FollowArtistsUsersOperationTypeEnum = {
  Artist: "artist",
  User: "user",
} as const;
export type FollowArtistsUsersOperationTypeEnum =
  (typeof FollowArtistsUsersOperationTypeEnum)[keyof typeof FollowArtistsUsersOperationTypeEnum];
/**
 * @export
 */
export const GetFollowedTypeEnum = {
  Artist: "artist",
} as const;
export type GetFollowedTypeEnum =
  (typeof GetFollowedTypeEnum)[keyof typeof GetFollowedTypeEnum];
/**
 * @export
 */
export const UnfollowArtistsUsersOperationTypeEnum = {
  Artist: "artist",
  User: "user",
} as const;
export type UnfollowArtistsUsersOperationTypeEnum =
  (typeof UnfollowArtistsUsersOperationTypeEnum)[keyof typeof UnfollowArtistsUsersOperationTypeEnum];
