/* tslint:disable */
/* eslint-disable */
/**
 * Spotify Web API with fixes and improvements from sonallux
 * You can use Spotify\'s Web API to discover music and podcasts, manage your Spotify library, control audio playback, and much more. Browse our available Web API endpoints using the sidebar at left, or via the navigation bar on top of this page on smaller screens.  In order to make successful Web API requests your app will need a valid access token. One can be obtained through <a href=\"https://developer.spotify.com/documentation/general/guides/authorization-guide/\">OAuth 2.0</a>.  The base URI for all Web API requests is `https://api.spotify.com/v1`.  Need help? See our <a href=\"https://developer.spotify.com/documentation/web-api/guides/\">Web API guides</a> for more information, or visit the <a href=\"https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer\">Spotify for Developers community forum</a> to ask questions and connect with other developers.
 *
 * The version of the OpenAPI document: 2025.5.18
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
  CurrentlyPlayingContextObject,
  CurrentlyPlayingObject,
  CursorPagingPlayHistoryObject,
  GetAnAlbum401Response,
  GetAUsersAvailableDevices200Response,
  QueueObject,
  StartAUsersPlaybackRequest,
  TransferAUsersPlaybackRequest,
} from "../models/index";
import * as runtime from "../runtime";

export interface PlayerApiAddToQueueRequest {
  uri: string;
  deviceId?: string;
}

export interface PlayerApiGetInformationAboutTheUsersCurrentPlaybackRequest {
  market?: string;
  additionalTypes?: string;
}

export interface PlayerApiGetRecentlyPlayedRequest {
  limit?: number;
  after?: number;
  before?: number;
}

export interface PlayerApiGetTheUsersCurrentlyPlayingTrackRequest {
  market?: string;
  additionalTypes?: string;
}

export interface PlayerApiPauseAUsersPlaybackRequest {
  deviceId?: string;
}

export interface PlayerApiSeekToPositionInCurrentlyPlayingTrackRequest {
  positionMs: number;
  deviceId?: string;
}

export interface PlayerApiSetRepeatModeOnUsersPlaybackRequest {
  state: string;
  deviceId?: string;
}

export interface PlayerApiSetVolumeForUsersPlaybackRequest {
  volumePercent: number;
  deviceId?: string;
}

export interface PlayerApiSkipUsersPlaybackToNextTrackRequest {
  deviceId?: string;
}

export interface PlayerApiSkipUsersPlaybackToPreviousTrackRequest {
  deviceId?: string;
}

export interface PlayerApiStartAUsersPlaybackOperationRequest {
  deviceId?: string;
  startAUsersPlaybackRequest?: StartAUsersPlaybackRequest;
}

export interface PlayerApiToggleShuffleForUsersPlaybackRequest {
  state: boolean;
  deviceId?: string;
}

export interface PlayerApiTransferAUsersPlaybackOperationRequest {
  transferAUsersPlaybackRequest?: TransferAUsersPlaybackRequest;
}

/**
 *
 */
export class PlayerApi extends runtime.BaseAPI {
  /**
   * Add an item to be played next in the user\'s current playback queue. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.
   * Add Item to Playback Queue
   */
  async addToQueueRaw(
    requestParameters: PlayerApiAddToQueueRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["uri"] == null) {
      throw new runtime.RequiredError(
        "uri",
        'Required parameter "uri" was null or undefined when calling addToQueue().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["uri"] != null) {
      queryParameters["uri"] = requestParameters["uri"];
    }

    if (requestParameters["deviceId"] != null) {
      queryParameters["device_id"] = requestParameters["deviceId"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-modify-playback-state"],
      );
    }

    let urlPath = `/me/player/queue`;

    const response = await this.request(
      {
        path: urlPath,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Add an item to be played next in the user\'s current playback queue. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.
   * Add Item to Playback Queue
   */
  async addToQueue(
    requestParameters: PlayerApiAddToQueueRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.addToQueueRaw(requestParameters, initOverrides);
  }

  /**
   * Get information about a user’s available Spotify Connect devices. Some device models are not supported and will not be listed in the API response.
   * Get Available Devices
   */
  async getAUsersAvailableDevicesRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<GetAUsersAvailableDevices200Response>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-read-playback-state"],
      );
    }

    let urlPath = `/me/player/devices`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get information about a user’s available Spotify Connect devices. Some device models are not supported and will not be listed in the API response.
   * Get Available Devices
   */
  async getAUsersAvailableDevices(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<GetAUsersAvailableDevices200Response> {
    const response = await this.getAUsersAvailableDevicesRaw(initOverrides);
    return await response.value();
  }

  /**
   * Get information about the user’s current playback state, including track or episode, progress, and active device.
   * Get Playback State
   */
  async getInformationAboutTheUsersCurrentPlaybackRaw(
    requestParameters: PlayerApiGetInformationAboutTheUsersCurrentPlaybackRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<CurrentlyPlayingContextObject>> {
    const queryParameters: any = {};

    if (requestParameters["market"] != null) {
      queryParameters["market"] = requestParameters["market"];
    }

    if (requestParameters["additionalTypes"] != null) {
      queryParameters["additional_types"] =
        requestParameters["additionalTypes"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-read-playback-state"],
      );
    }

    let urlPath = `/me/player`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get information about the user’s current playback state, including track or episode, progress, and active device.
   * Get Playback State
   */
  async getInformationAboutTheUsersCurrentPlayback(
    requestParameters: PlayerApiGetInformationAboutTheUsersCurrentPlaybackRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<CurrentlyPlayingContextObject | null | undefined> {
    const response = await this.getInformationAboutTheUsersCurrentPlaybackRaw(
      requestParameters,
      initOverrides,
    );
    switch (response.raw.status) {
      case 200:
        return await response.value();
      case 204:
        return null;
      default:
        return await response.value();
    }
  }

  /**
   * Get the list of objects that make up the user\'s queue.
   * Get the User\'s Queue
   */
  async getQueueRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<QueueObject>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-read-currently-playing", "user-read-playback-state"],
      );
    }

    let urlPath = `/me/player/queue`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get the list of objects that make up the user\'s queue.
   * Get the User\'s Queue
   */
  async getQueue(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<QueueObject> {
    const response = await this.getQueueRaw(initOverrides);
    return await response.value();
  }

  /**
   * Get tracks from the current user\'s recently played tracks. _**Note**: Currently doesn\'t support podcast episodes._
   * Get Recently Played Tracks
   */
  async getRecentlyPlayedRaw(
    requestParameters: PlayerApiGetRecentlyPlayedRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<CursorPagingPlayHistoryObject>> {
    const queryParameters: any = {};

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    if (requestParameters["after"] != null) {
      queryParameters["after"] = requestParameters["after"];
    }

    if (requestParameters["before"] != null) {
      queryParameters["before"] = requestParameters["before"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-read-recently-played"],
      );
    }

    let urlPath = `/me/player/recently-played`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get tracks from the current user\'s recently played tracks. _**Note**: Currently doesn\'t support podcast episodes._
   * Get Recently Played Tracks
   */
  async getRecentlyPlayed(
    requestParameters: PlayerApiGetRecentlyPlayedRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<CursorPagingPlayHistoryObject> {
    const response = await this.getRecentlyPlayedRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Get the object currently being played on the user\'s Spotify account.
   * Get Currently Playing Track
   */
  async getTheUsersCurrentlyPlayingTrackRaw(
    requestParameters: PlayerApiGetTheUsersCurrentlyPlayingTrackRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<CurrentlyPlayingObject>> {
    const queryParameters: any = {};

    if (requestParameters["market"] != null) {
      queryParameters["market"] = requestParameters["market"];
    }

    if (requestParameters["additionalTypes"] != null) {
      queryParameters["additional_types"] =
        requestParameters["additionalTypes"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-read-currently-playing"],
      );
    }

    let urlPath = `/me/player/currently-playing`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get the object currently being played on the user\'s Spotify account.
   * Get Currently Playing Track
   */
  async getTheUsersCurrentlyPlayingTrack(
    requestParameters: PlayerApiGetTheUsersCurrentlyPlayingTrackRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<CurrentlyPlayingObject> {
    const response = await this.getTheUsersCurrentlyPlayingTrackRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Pause playback on the user\'s account. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.
   * Pause Playback
   */
  async pauseAUsersPlaybackRaw(
    requestParameters: PlayerApiPauseAUsersPlaybackRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    const queryParameters: any = {};

    if (requestParameters["deviceId"] != null) {
      queryParameters["device_id"] = requestParameters["deviceId"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-modify-playback-state"],
      );
    }

    let urlPath = `/me/player/pause`;

    const response = await this.request(
      {
        path: urlPath,
        method: "PUT",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Pause playback on the user\'s account. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.
   * Pause Playback
   */
  async pauseAUsersPlayback(
    requestParameters: PlayerApiPauseAUsersPlaybackRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.pauseAUsersPlaybackRaw(requestParameters, initOverrides);
  }

  /**
   * Seeks to the given position in the user’s currently playing track. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.
   * Seek To Position
   */
  async seekToPositionInCurrentlyPlayingTrackRaw(
    requestParameters: PlayerApiSeekToPositionInCurrentlyPlayingTrackRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["positionMs"] == null) {
      throw new runtime.RequiredError(
        "positionMs",
        'Required parameter "positionMs" was null or undefined when calling seekToPositionInCurrentlyPlayingTrack().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["positionMs"] != null) {
      queryParameters["position_ms"] = requestParameters["positionMs"];
    }

    if (requestParameters["deviceId"] != null) {
      queryParameters["device_id"] = requestParameters["deviceId"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-modify-playback-state"],
      );
    }

    let urlPath = `/me/player/seek`;

    const response = await this.request(
      {
        path: urlPath,
        method: "PUT",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Seeks to the given position in the user’s currently playing track. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.
   * Seek To Position
   */
  async seekToPositionInCurrentlyPlayingTrack(
    requestParameters: PlayerApiSeekToPositionInCurrentlyPlayingTrackRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.seekToPositionInCurrentlyPlayingTrackRaw(
      requestParameters,
      initOverrides,
    );
  }

  /**
   * Set the repeat mode for the user\'s playback. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.
   * Set Repeat Mode
   */
  async setRepeatModeOnUsersPlaybackRaw(
    requestParameters: PlayerApiSetRepeatModeOnUsersPlaybackRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["state"] == null) {
      throw new runtime.RequiredError(
        "state",
        'Required parameter "state" was null or undefined when calling setRepeatModeOnUsersPlayback().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["state"] != null) {
      queryParameters["state"] = requestParameters["state"];
    }

    if (requestParameters["deviceId"] != null) {
      queryParameters["device_id"] = requestParameters["deviceId"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-modify-playback-state"],
      );
    }

    let urlPath = `/me/player/repeat`;

    const response = await this.request(
      {
        path: urlPath,
        method: "PUT",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Set the repeat mode for the user\'s playback. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.
   * Set Repeat Mode
   */
  async setRepeatModeOnUsersPlayback(
    requestParameters: PlayerApiSetRepeatModeOnUsersPlaybackRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.setRepeatModeOnUsersPlaybackRaw(
      requestParameters,
      initOverrides,
    );
  }

  /**
   * Set the volume for the user’s current playback device. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.
   * Set Playback Volume
   */
  async setVolumeForUsersPlaybackRaw(
    requestParameters: PlayerApiSetVolumeForUsersPlaybackRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["volumePercent"] == null) {
      throw new runtime.RequiredError(
        "volumePercent",
        'Required parameter "volumePercent" was null or undefined when calling setVolumeForUsersPlayback().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["volumePercent"] != null) {
      queryParameters["volume_percent"] = requestParameters["volumePercent"];
    }

    if (requestParameters["deviceId"] != null) {
      queryParameters["device_id"] = requestParameters["deviceId"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-modify-playback-state"],
      );
    }

    let urlPath = `/me/player/volume`;

    const response = await this.request(
      {
        path: urlPath,
        method: "PUT",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Set the volume for the user’s current playback device. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.
   * Set Playback Volume
   */
  async setVolumeForUsersPlayback(
    requestParameters: PlayerApiSetVolumeForUsersPlaybackRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.setVolumeForUsersPlaybackRaw(requestParameters, initOverrides);
  }

  /**
   * Skips to next track in the user’s queue. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.
   * Skip To Next
   */
  async skipUsersPlaybackToNextTrackRaw(
    requestParameters: PlayerApiSkipUsersPlaybackToNextTrackRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    const queryParameters: any = {};

    if (requestParameters["deviceId"] != null) {
      queryParameters["device_id"] = requestParameters["deviceId"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-modify-playback-state"],
      );
    }

    let urlPath = `/me/player/next`;

    const response = await this.request(
      {
        path: urlPath,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Skips to next track in the user’s queue. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.
   * Skip To Next
   */
  async skipUsersPlaybackToNextTrack(
    requestParameters: PlayerApiSkipUsersPlaybackToNextTrackRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.skipUsersPlaybackToNextTrackRaw(
      requestParameters,
      initOverrides,
    );
  }

  /**
   * Skips to previous track in the user’s queue. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.
   * Skip To Previous
   */
  async skipUsersPlaybackToPreviousTrackRaw(
    requestParameters: PlayerApiSkipUsersPlaybackToPreviousTrackRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    const queryParameters: any = {};

    if (requestParameters["deviceId"] != null) {
      queryParameters["device_id"] = requestParameters["deviceId"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-modify-playback-state"],
      );
    }

    let urlPath = `/me/player/previous`;

    const response = await this.request(
      {
        path: urlPath,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Skips to previous track in the user’s queue. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.
   * Skip To Previous
   */
  async skipUsersPlaybackToPreviousTrack(
    requestParameters: PlayerApiSkipUsersPlaybackToPreviousTrackRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.skipUsersPlaybackToPreviousTrackRaw(
      requestParameters,
      initOverrides,
    );
  }

  /**
   * Start a new context or resume current playback on the user\'s active device. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.
   * Start/Resume Playback
   */
  async startAUsersPlaybackRaw(
    requestParameters: PlayerApiStartAUsersPlaybackOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    const queryParameters: any = {};

    if (requestParameters["deviceId"] != null) {
      queryParameters["device_id"] = requestParameters["deviceId"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-modify-playback-state"],
      );
    }

    let urlPath = `/me/player/play`;

    const response = await this.request(
      {
        path: urlPath,
        method: "PUT",
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters["startAUsersPlaybackRequest"],
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Start a new context or resume current playback on the user\'s active device. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.
   * Start/Resume Playback
   */
  async startAUsersPlayback(
    requestParameters: PlayerApiStartAUsersPlaybackOperationRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.startAUsersPlaybackRaw(requestParameters, initOverrides);
  }

  /**
   * Toggle shuffle on or off for user’s playback. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.
   * Toggle Playback Shuffle
   */
  async toggleShuffleForUsersPlaybackRaw(
    requestParameters: PlayerApiToggleShuffleForUsersPlaybackRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["state"] == null) {
      throw new runtime.RequiredError(
        "state",
        'Required parameter "state" was null or undefined when calling toggleShuffleForUsersPlayback().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["state"] != null) {
      queryParameters["state"] = requestParameters["state"];
    }

    if (requestParameters["deviceId"] != null) {
      queryParameters["device_id"] = requestParameters["deviceId"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-modify-playback-state"],
      );
    }

    let urlPath = `/me/player/shuffle`;

    const response = await this.request(
      {
        path: urlPath,
        method: "PUT",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Toggle shuffle on or off for user’s playback. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.
   * Toggle Playback Shuffle
   */
  async toggleShuffleForUsersPlayback(
    requestParameters: PlayerApiToggleShuffleForUsersPlaybackRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.toggleShuffleForUsersPlaybackRaw(
      requestParameters,
      initOverrides,
    );
  }

  /**
   * Transfer playback to a new device and optionally begin playback. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.
   * Transfer Playback
   */
  async transferAUsersPlaybackRaw(
    requestParameters: PlayerApiTransferAUsersPlaybackOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-modify-playback-state"],
      );
    }

    let urlPath = `/me/player`;

    const response = await this.request(
      {
        path: urlPath,
        method: "PUT",
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters["transferAUsersPlaybackRequest"],
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Transfer playback to a new device and optionally begin playback. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.
   * Transfer Playback
   */
  async transferAUsersPlayback(
    requestParameters: PlayerApiTransferAUsersPlaybackOperationRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.transferAUsersPlaybackRaw(requestParameters, initOverrides);
  }
}
