/* tslint:disable */
/* eslint-disable */
/**
 * Spotify Web API with fixes and improvements from sonallux
 * You can use Spotify\'s Web API to discover music and podcasts, manage your Spotify library, control audio playback, and much more. Browse our available Web API endpoints using the sidebar at left, or via the navigation bar on top of this page on smaller screens.  In order to make successful Web API requests your app will need a valid access token. One can be obtained through <a href=\"https://developer.spotify.com/documentation/general/guides/authorization-guide/\">OAuth 2.0</a>.  The base URI for all Web API requests is `https://api.spotify.com/v1`.  Need help? See our <a href=\"https://developer.spotify.com/documentation/web-api/guides/\">Web API guides</a> for more information, or visit the <a href=\"https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer\">Spotify for Developers community forum</a> to ask questions and connect with other developers.
 *
 * The version of the OpenAPI document: 2025.5.18
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
  AddTracksToPlaylistRequest,
  ChangePlaylistDetailsRequest,
  CreatePlaylistRequest,
  FollowPlaylistRequest,
  GetAnAlbum401Response,
  ImageObject,
  PagingFeaturedPlaylistObject,
  PagingPlaylistObject,
  PagingPlaylistTrackObject,
  PlaylistObject,
  RemoveTracksPlaylistRequest,
  ReorderOrReplacePlaylistsTracks200Response,
  ReorderOrReplacePlaylistsTracksRequest,
} from "../models/index";
import * as runtime from "../runtime";

export interface PlaylistsApiAddTracksToPlaylistOperationRequest {
  playlistId: string;
  position?: number;
  uris?: string;
  addTracksToPlaylistRequest?: AddTracksToPlaylistRequest;
}

export interface PlaylistsApiChangePlaylistDetailsOperationRequest {
  playlistId: string;
  changePlaylistDetailsRequest?: ChangePlaylistDetailsRequest;
}

export interface PlaylistsApiCheckIfUserFollowsPlaylistRequest {
  playlistId: string;
  ids?: string;
}

export interface PlaylistsApiCreatePlaylistOperationRequest {
  userId: string;
  createPlaylistRequest?: CreatePlaylistRequest;
}

export interface PlaylistsApiFollowPlaylistOperationRequest {
  playlistId: string;
  followPlaylistRequest?: FollowPlaylistRequest;
}

export interface PlaylistsApiGetACategoriesPlaylistsRequest {
  categoryId: string;
  limit?: number;
  offset?: number;
}

export interface PlaylistsApiGetAListOfCurrentUsersPlaylistsRequest {
  limit?: number;
  offset?: number;
}

export interface PlaylistsApiGetFeaturedPlaylistsRequest {
  locale?: string;
  limit?: number;
  offset?: number;
}

export interface PlaylistsApiGetListUsersPlaylistsRequest {
  userId: string;
  limit?: number;
  offset?: number;
}

export interface PlaylistsApiGetPlaylistRequest {
  playlistId: string;
  market?: string;
  fields?: string;
  additionalTypes?: string;
}

export interface PlaylistsApiGetPlaylistCoverRequest {
  playlistId: string;
}

export interface PlaylistsApiGetPlaylistsTracksRequest {
  playlistId: string;
  market?: string;
  fields?: string;
  limit?: number;
  offset?: number;
  additionalTypes?: string;
}

export interface PlaylistsApiRemoveTracksPlaylistOperationRequest {
  playlistId: string;
  removeTracksPlaylistRequest?: RemoveTracksPlaylistRequest;
}

export interface PlaylistsApiReorderOrReplacePlaylistsTracksOperationRequest {
  playlistId: string;
  uris?: string;
  reorderOrReplacePlaylistsTracksRequest?: ReorderOrReplacePlaylistsTracksRequest;
}

export interface PlaylistsApiUnfollowPlaylistRequest {
  playlistId: string;
}

export interface PlaylistsApiUploadCustomPlaylistCoverRequest {
  playlistId: string;
  body: string;
}

/**
 *
 */
export class PlaylistsApi extends runtime.BaseAPI {
  /**
   * Add one or more items to a user\'s playlist.
   * Add Items to Playlist
   */
  async addTracksToPlaylistRaw(
    requestParameters: PlaylistsApiAddTracksToPlaylistOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ReorderOrReplacePlaylistsTracks200Response>> {
    if (requestParameters["playlistId"] == null) {
      throw new runtime.RequiredError(
        "playlistId",
        'Required parameter "playlistId" was null or undefined when calling addTracksToPlaylist().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["position"] != null) {
      queryParameters["position"] = requestParameters["position"];
    }

    if (requestParameters["uris"] != null) {
      queryParameters["uris"] = requestParameters["uris"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["playlist-modify-public", "playlist-modify-private"],
      );
    }

    let urlPath = `/playlists/{playlist_id}/tracks`;
    urlPath = urlPath.replace(
      `{${"playlist_id"}}`,
      encodeURIComponent(String(requestParameters["playlistId"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters["addTracksToPlaylistRequest"],
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Add one or more items to a user\'s playlist.
   * Add Items to Playlist
   */
  async addTracksToPlaylist(
    requestParameters: PlaylistsApiAddTracksToPlaylistOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ReorderOrReplacePlaylistsTracks200Response> {
    const response = await this.addTracksToPlaylistRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Change a playlist\'s name and public/private state. (The user must, of course, own the playlist.)
   * Change Playlist Details
   */
  async changePlaylistDetailsRaw(
    requestParameters: PlaylistsApiChangePlaylistDetailsOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["playlistId"] == null) {
      throw new runtime.RequiredError(
        "playlistId",
        'Required parameter "playlistId" was null or undefined when calling changePlaylistDetails().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["playlist-modify-public", "playlist-modify-private"],
      );
    }

    let urlPath = `/playlists/{playlist_id}`;
    urlPath = urlPath.replace(
      `{${"playlist_id"}}`,
      encodeURIComponent(String(requestParameters["playlistId"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "PUT",
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters["changePlaylistDetailsRequest"],
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Change a playlist\'s name and public/private state. (The user must, of course, own the playlist.)
   * Change Playlist Details
   */
  async changePlaylistDetails(
    requestParameters: PlaylistsApiChangePlaylistDetailsOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.changePlaylistDetailsRaw(requestParameters, initOverrides);
  }

  /**
   * Check to see if the current user is following a specified playlist.
   * Check if Current User Follows Playlist
   */
  async checkIfUserFollowsPlaylistRaw(
    requestParameters: PlaylistsApiCheckIfUserFollowsPlaylistRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<boolean>>> {
    if (requestParameters["playlistId"] == null) {
      throw new runtime.RequiredError(
        "playlistId",
        'Required parameter "playlistId" was null or undefined when calling checkIfUserFollowsPlaylist().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["ids"] != null) {
      queryParameters["ids"] = requestParameters["ids"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        [],
      );
    }

    let urlPath = `/playlists/{playlist_id}/followers/contains`;
    urlPath = urlPath.replace(
      `{${"playlist_id"}}`,
      encodeURIComponent(String(requestParameters["playlistId"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse<any>(response);
  }

  /**
   * Check to see if the current user is following a specified playlist.
   * Check if Current User Follows Playlist
   */
  async checkIfUserFollowsPlaylist(
    requestParameters: PlaylistsApiCheckIfUserFollowsPlaylistRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<boolean>> {
    const response = await this.checkIfUserFollowsPlaylistRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Create a playlist for a Spotify user. (The playlist will be empty until you [add tracks](/documentation/web-api/reference/add-tracks-to-playlist).) Each user is generally limited to a maximum of 11000 playlists.
   * Create Playlist
   */
  async createPlaylistRaw(
    requestParameters: PlaylistsApiCreatePlaylistOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PlaylistObject>> {
    if (requestParameters["userId"] == null) {
      throw new runtime.RequiredError(
        "userId",
        'Required parameter "userId" was null or undefined when calling createPlaylist().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["playlist-modify-public", "playlist-modify-private"],
      );
    }

    let urlPath = `/users/{user_id}/playlists`;
    urlPath = urlPath.replace(
      `{${"user_id"}}`,
      encodeURIComponent(String(requestParameters["userId"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters["createPlaylistRequest"],
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Create a playlist for a Spotify user. (The playlist will be empty until you [add tracks](/documentation/web-api/reference/add-tracks-to-playlist).) Each user is generally limited to a maximum of 11000 playlists.
   * Create Playlist
   */
  async createPlaylist(
    requestParameters: PlaylistsApiCreatePlaylistOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PlaylistObject> {
    const response = await this.createPlaylistRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Add the current user as a follower of a playlist.
   * Follow Playlist
   */
  async followPlaylistRaw(
    requestParameters: PlaylistsApiFollowPlaylistOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["playlistId"] == null) {
      throw new runtime.RequiredError(
        "playlistId",
        'Required parameter "playlistId" was null or undefined when calling followPlaylist().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["playlist-modify-public", "playlist-modify-private"],
      );
    }

    let urlPath = `/playlists/{playlist_id}/followers`;
    urlPath = urlPath.replace(
      `{${"playlist_id"}}`,
      encodeURIComponent(String(requestParameters["playlistId"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "PUT",
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters["followPlaylistRequest"],
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Add the current user as a follower of a playlist.
   * Follow Playlist
   */
  async followPlaylist(
    requestParameters: PlaylistsApiFollowPlaylistOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.followPlaylistRaw(requestParameters, initOverrides);
  }

  /**
   * Get a list of Spotify playlists tagged with a particular category.
   * Get Category\'s Playlists
   * @deprecated
   */
  async getACategoriesPlaylistsRaw(
    requestParameters: PlaylistsApiGetACategoriesPlaylistsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PagingFeaturedPlaylistObject>> {
    if (requestParameters["categoryId"] == null) {
      throw new runtime.RequiredError(
        "categoryId",
        'Required parameter "categoryId" was null or undefined when calling getACategoriesPlaylists().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    if (requestParameters["offset"] != null) {
      queryParameters["offset"] = requestParameters["offset"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        [],
      );
    }

    let urlPath = `/browse/categories/{category_id}/playlists`;
    urlPath = urlPath.replace(
      `{${"category_id"}}`,
      encodeURIComponent(String(requestParameters["categoryId"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get a list of Spotify playlists tagged with a particular category.
   * Get Category\'s Playlists
   * @deprecated
   */
  async getACategoriesPlaylists(
    requestParameters: PlaylistsApiGetACategoriesPlaylistsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PagingFeaturedPlaylistObject> {
    const response = await this.getACategoriesPlaylistsRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Get a list of the playlists owned or followed by the current Spotify user.
   * Get Current User\'s Playlists
   */
  async getAListOfCurrentUsersPlaylistsRaw(
    requestParameters: PlaylistsApiGetAListOfCurrentUsersPlaylistsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PagingPlaylistObject>> {
    const queryParameters: any = {};

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    if (requestParameters["offset"] != null) {
      queryParameters["offset"] = requestParameters["offset"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["playlist-read-private"],
      );
    }

    let urlPath = `/me/playlists`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get a list of the playlists owned or followed by the current Spotify user.
   * Get Current User\'s Playlists
   */
  async getAListOfCurrentUsersPlaylists(
    requestParameters: PlaylistsApiGetAListOfCurrentUsersPlaylistsRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PagingPlaylistObject> {
    const response = await this.getAListOfCurrentUsersPlaylistsRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Get a list of Spotify featured playlists (shown, for example, on a Spotify player\'s \'Browse\' tab).
   * Get Featured Playlists
   * @deprecated
   */
  async getFeaturedPlaylistsRaw(
    requestParameters: PlaylistsApiGetFeaturedPlaylistsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PagingFeaturedPlaylistObject>> {
    const queryParameters: any = {};

    if (requestParameters["locale"] != null) {
      queryParameters["locale"] = requestParameters["locale"];
    }

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    if (requestParameters["offset"] != null) {
      queryParameters["offset"] = requestParameters["offset"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        [],
      );
    }

    let urlPath = `/browse/featured-playlists`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get a list of Spotify featured playlists (shown, for example, on a Spotify player\'s \'Browse\' tab).
   * Get Featured Playlists
   * @deprecated
   */
  async getFeaturedPlaylists(
    requestParameters: PlaylistsApiGetFeaturedPlaylistsRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PagingFeaturedPlaylistObject> {
    const response = await this.getFeaturedPlaylistsRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Get a list of the playlists owned or followed by a Spotify user.
   * Get User\'s Playlists
   */
  async getListUsersPlaylistsRaw(
    requestParameters: PlaylistsApiGetListUsersPlaylistsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PagingPlaylistObject>> {
    if (requestParameters["userId"] == null) {
      throw new runtime.RequiredError(
        "userId",
        'Required parameter "userId" was null or undefined when calling getListUsersPlaylists().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    if (requestParameters["offset"] != null) {
      queryParameters["offset"] = requestParameters["offset"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["playlist-read-private", "playlist-read-collaborative"],
      );
    }

    let urlPath = `/users/{user_id}/playlists`;
    urlPath = urlPath.replace(
      `{${"user_id"}}`,
      encodeURIComponent(String(requestParameters["userId"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get a list of the playlists owned or followed by a Spotify user.
   * Get User\'s Playlists
   */
  async getListUsersPlaylists(
    requestParameters: PlaylistsApiGetListUsersPlaylistsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PagingPlaylistObject> {
    const response = await this.getListUsersPlaylistsRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Get a playlist owned by a Spotify user.
   * Get Playlist
   */
  async getPlaylistRaw(
    requestParameters: PlaylistsApiGetPlaylistRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PlaylistObject>> {
    if (requestParameters["playlistId"] == null) {
      throw new runtime.RequiredError(
        "playlistId",
        'Required parameter "playlistId" was null or undefined when calling getPlaylist().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["market"] != null) {
      queryParameters["market"] = requestParameters["market"];
    }

    if (requestParameters["fields"] != null) {
      queryParameters["fields"] = requestParameters["fields"];
    }

    if (requestParameters["additionalTypes"] != null) {
      queryParameters["additional_types"] =
        requestParameters["additionalTypes"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        [],
      );
    }

    let urlPath = `/playlists/{playlist_id}`;
    urlPath = urlPath.replace(
      `{${"playlist_id"}}`,
      encodeURIComponent(String(requestParameters["playlistId"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get a playlist owned by a Spotify user.
   * Get Playlist
   */
  async getPlaylist(
    requestParameters: PlaylistsApiGetPlaylistRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PlaylistObject> {
    const response = await this.getPlaylistRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Get the current image associated with a specific playlist.
   * Get Playlist Cover Image
   */
  async getPlaylistCoverRaw(
    requestParameters: PlaylistsApiGetPlaylistCoverRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<ImageObject>>> {
    if (requestParameters["playlistId"] == null) {
      throw new runtime.RequiredError(
        "playlistId",
        'Required parameter "playlistId" was null or undefined when calling getPlaylistCover().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        [],
      );
    }

    let urlPath = `/playlists/{playlist_id}/images`;
    urlPath = urlPath.replace(
      `{${"playlist_id"}}`,
      encodeURIComponent(String(requestParameters["playlistId"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get the current image associated with a specific playlist.
   * Get Playlist Cover Image
   */
  async getPlaylistCover(
    requestParameters: PlaylistsApiGetPlaylistCoverRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<ImageObject>> {
    const response = await this.getPlaylistCoverRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Get full details of the items of a playlist owned by a Spotify user.
   * Get Playlist Items
   */
  async getPlaylistsTracksRaw(
    requestParameters: PlaylistsApiGetPlaylistsTracksRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PagingPlaylistTrackObject>> {
    if (requestParameters["playlistId"] == null) {
      throw new runtime.RequiredError(
        "playlistId",
        'Required parameter "playlistId" was null or undefined when calling getPlaylistsTracks().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["market"] != null) {
      queryParameters["market"] = requestParameters["market"];
    }

    if (requestParameters["fields"] != null) {
      queryParameters["fields"] = requestParameters["fields"];
    }

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    if (requestParameters["offset"] != null) {
      queryParameters["offset"] = requestParameters["offset"];
    }

    if (requestParameters["additionalTypes"] != null) {
      queryParameters["additional_types"] =
        requestParameters["additionalTypes"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["playlist-read-private"],
      );
    }

    let urlPath = `/playlists/{playlist_id}/tracks`;
    urlPath = urlPath.replace(
      `{${"playlist_id"}}`,
      encodeURIComponent(String(requestParameters["playlistId"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get full details of the items of a playlist owned by a Spotify user.
   * Get Playlist Items
   */
  async getPlaylistsTracks(
    requestParameters: PlaylistsApiGetPlaylistsTracksRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PagingPlaylistTrackObject> {
    const response = await this.getPlaylistsTracksRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Remove one or more items from a user\'s playlist.
   * Remove Playlist Items
   */
  async removeTracksPlaylistRaw(
    requestParameters: PlaylistsApiRemoveTracksPlaylistOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ReorderOrReplacePlaylistsTracks200Response>> {
    if (requestParameters["playlistId"] == null) {
      throw new runtime.RequiredError(
        "playlistId",
        'Required parameter "playlistId" was null or undefined when calling removeTracksPlaylist().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["playlist-modify-public", "playlist-modify-private"],
      );
    }

    let urlPath = `/playlists/{playlist_id}/tracks`;
    urlPath = urlPath.replace(
      `{${"playlist_id"}}`,
      encodeURIComponent(String(requestParameters["playlistId"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "DELETE",
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters["removeTracksPlaylistRequest"],
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Remove one or more items from a user\'s playlist.
   * Remove Playlist Items
   */
  async removeTracksPlaylist(
    requestParameters: PlaylistsApiRemoveTracksPlaylistOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ReorderOrReplacePlaylistsTracks200Response> {
    const response = await this.removeTracksPlaylistRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Either reorder or replace items in a playlist depending on the request\'s parameters. To reorder items, include `range_start`, `insert_before`, `range_length` and `snapshot_id` in the request\'s body. To replace items, include `uris` as either a query parameter or in the request\'s body. Replacing items in a playlist will overwrite its existing items. This operation can be used for replacing or clearing items in a playlist. <br/> **Note**: Replace and reorder are mutually exclusive operations which share the same endpoint, but have different parameters. These operations can\'t be applied together in a single request.
   * Update Playlist Items
   */
  async reorderOrReplacePlaylistsTracksRaw(
    requestParameters: PlaylistsApiReorderOrReplacePlaylistsTracksOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ReorderOrReplacePlaylistsTracks200Response>> {
    if (requestParameters["playlistId"] == null) {
      throw new runtime.RequiredError(
        "playlistId",
        'Required parameter "playlistId" was null or undefined when calling reorderOrReplacePlaylistsTracks().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["uris"] != null) {
      queryParameters["uris"] = requestParameters["uris"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["playlist-modify-public", "playlist-modify-private"],
      );
    }

    let urlPath = `/playlists/{playlist_id}/tracks`;
    urlPath = urlPath.replace(
      `{${"playlist_id"}}`,
      encodeURIComponent(String(requestParameters["playlistId"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "PUT",
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters["reorderOrReplacePlaylistsTracksRequest"],
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Either reorder or replace items in a playlist depending on the request\'s parameters. To reorder items, include `range_start`, `insert_before`, `range_length` and `snapshot_id` in the request\'s body. To replace items, include `uris` as either a query parameter or in the request\'s body. Replacing items in a playlist will overwrite its existing items. This operation can be used for replacing or clearing items in a playlist. <br/> **Note**: Replace and reorder are mutually exclusive operations which share the same endpoint, but have different parameters. These operations can\'t be applied together in a single request.
   * Update Playlist Items
   */
  async reorderOrReplacePlaylistsTracks(
    requestParameters: PlaylistsApiReorderOrReplacePlaylistsTracksOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ReorderOrReplacePlaylistsTracks200Response> {
    const response = await this.reorderOrReplacePlaylistsTracksRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Remove the current user as a follower of a playlist.
   * Unfollow Playlist
   */
  async unfollowPlaylistRaw(
    requestParameters: PlaylistsApiUnfollowPlaylistRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["playlistId"] == null) {
      throw new runtime.RequiredError(
        "playlistId",
        'Required parameter "playlistId" was null or undefined when calling unfollowPlaylist().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["playlist-modify-public", "playlist-modify-private"],
      );
    }

    let urlPath = `/playlists/{playlist_id}/followers`;
    urlPath = urlPath.replace(
      `{${"playlist_id"}}`,
      encodeURIComponent(String(requestParameters["playlistId"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "DELETE",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Remove the current user as a follower of a playlist.
   * Unfollow Playlist
   */
  async unfollowPlaylist(
    requestParameters: PlaylistsApiUnfollowPlaylistRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.unfollowPlaylistRaw(requestParameters, initOverrides);
  }

  /**
   * Replace the image used to represent a specific playlist.
   * Add Custom Playlist Cover Image
   */
  async uploadCustomPlaylistCoverRaw(
    requestParameters: PlaylistsApiUploadCustomPlaylistCoverRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["playlistId"] == null) {
      throw new runtime.RequiredError(
        "playlistId",
        'Required parameter "playlistId" was null or undefined when calling uploadCustomPlaylistCover().',
      );
    }

    if (requestParameters["body"] == null) {
      throw new runtime.RequiredError(
        "body",
        'Required parameter "body" was null or undefined when calling uploadCustomPlaylistCover().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "image/jpeg";

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        [
          "ugc-image-upload",
          "playlist-modify-public",
          "playlist-modify-private",
        ],
      );
    }

    let urlPath = `/playlists/{playlist_id}/images`;
    urlPath = urlPath.replace(
      `{${"playlist_id"}}`,
      encodeURIComponent(String(requestParameters["playlistId"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "PUT",
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters["body"] as any,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Replace the image used to represent a specific playlist.
   * Add Custom Playlist Cover Image
   */
  async uploadCustomPlaylistCover(
    requestParameters: PlaylistsApiUploadCustomPlaylistCoverRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.uploadCustomPlaylistCoverRaw(requestParameters, initOverrides);
  }
}
