/* tslint:disable */
/* eslint-disable */
/**
 * Spotify Web API with fixes and improvements from sonallux
 * You can use Spotify\'s Web API to discover music and podcasts, manage your Spotify library, control audio playback, and much more. Browse our available Web API endpoints using the sidebar at left, or via the navigation bar on top of this page on smaller screens.  In order to make successful Web API requests your app will need a valid access token. One can be obtained through <a href=\"https://developer.spotify.com/documentation/general/guides/authorization-guide/\">OAuth 2.0</a>.  The base URI for all Web API requests is `https://api.spotify.com/v1`.  Need help? See our <a href=\"https://developer.spotify.com/documentation/web-api/guides/\">Web API guides</a> for more information, or visit the <a href=\"https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer\">Spotify for Developers community forum</a> to ask questions and connect with other developers.
 *
 * The version of the OpenAPI document: 2025.5.18
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { InlineObject, InlineObject14 } from "../models/index";
import * as runtime from "../runtime";

export interface SearchApiSearchRequest {
  q: string;
  type: Array<SearchTypeEnum>;
  market?: string;
  limit?: number;
  offset?: number;
  includeExternal?: SearchIncludeExternalEnum;
}

/**
 *
 */
export class SearchApi extends runtime.BaseAPI {
  /**
   * Get Spotify catalog information about albums, artists, playlists, tracks, shows, episodes or audiobooks that match a keyword string. Audiobooks are only available within the US, UK, Canada, Ireland, New Zealand and Australia markets.
   * Search for Item
   */
  async searchRaw(
    requestParameters: SearchApiSearchRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<InlineObject14>> {
    if (requestParameters["q"] == null) {
      throw new runtime.RequiredError(
        "q",
        'Required parameter "q" was null or undefined when calling search().',
      );
    }

    if (requestParameters["type"] == null) {
      throw new runtime.RequiredError(
        "type",
        'Required parameter "type" was null or undefined when calling search().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["q"] != null) {
      queryParameters["q"] = requestParameters["q"];
    }

    if (requestParameters["type"] != null) {
      queryParameters["type"] = requestParameters["type"]!.join(
        runtime.COLLECTION_FORMATS["csv"],
      );
    }

    if (requestParameters["market"] != null) {
      queryParameters["market"] = requestParameters["market"];
    }

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    if (requestParameters["offset"] != null) {
      queryParameters["offset"] = requestParameters["offset"];
    }

    if (requestParameters["includeExternal"] != null) {
      queryParameters["include_external"] =
        requestParameters["includeExternal"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        [],
      );
    }

    let urlPath = `/search`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get Spotify catalog information about albums, artists, playlists, tracks, shows, episodes or audiobooks that match a keyword string. Audiobooks are only available within the US, UK, Canada, Ireland, New Zealand and Australia markets.
   * Search for Item
   */
  async search(
    requestParameters: SearchApiSearchRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<InlineObject14> {
    const response = await this.searchRaw(requestParameters, initOverrides);
    return await response.value();
  }
}

/**
 * @export
 */
export const SearchTypeEnum = {
  Album: "album",
  Artist: "artist",
  Playlist: "playlist",
  Track: "track",
  Show: "show",
  Episode: "episode",
  Audiobook: "audiobook",
} as const;
export type SearchTypeEnum =
  (typeof SearchTypeEnum)[keyof typeof SearchTypeEnum];
/**
 * @export
 */
export const SearchIncludeExternalEnum = {
  Audio: "audio",
} as const;
export type SearchIncludeExternalEnum =
  (typeof SearchIncludeExternalEnum)[keyof typeof SearchIncludeExternalEnum];
