/* tslint:disable */
/* eslint-disable */
/**
 * Spotify Web API with fixes and improvements from sonallux
 * You can use Spotify\'s Web API to discover music and podcasts, manage your Spotify library, control audio playback, and much more. Browse our available Web API endpoints using the sidebar at left, or via the navigation bar on top of this page on smaller screens.  In order to make successful Web API requests your app will need a valid access token. One can be obtained through <a href=\"https://developer.spotify.com/documentation/general/guides/authorization-guide/\">OAuth 2.0</a>.  The base URI for all Web API requests is `https://api.spotify.com/v1`.  Need help? See our <a href=\"https://developer.spotify.com/documentation/web-api/guides/\">Web API guides</a> for more information, or visit the <a href=\"https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer\">Spotify for Developers community forum</a> to ask questions and connect with other developers.
 *
 * The version of the OpenAPI document: 2025.5.18
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
  InlineObject,
  InlineObject13,
  PagingSavedShowObject,
  PagingSimplifiedEpisodeObject,
  SaveShowsUserRequest,
  ShowObject,
} from "../models/index";
import * as runtime from "../runtime";

export interface ShowsApiCheckUsersSavedShowsRequest {
  ids: string;
}

export interface ShowsApiGetAShowRequest {
  id: string;
  market?: string;
}

export interface ShowsApiGetAShowsEpisodesRequest {
  id: string;
  market?: string;
  limit?: number;
  offset?: number;
}

export interface ShowsApiGetMultipleShowsRequest {
  ids: string;
  market?: string;
}

export interface ShowsApiGetUsersSavedShowsRequest {
  limit?: number;
  offset?: number;
}

export interface ShowsApiRemoveShowsUserRequest {
  ids: string;
  market?: string;
  saveShowsUserRequest?: SaveShowsUserRequest;
}

export interface ShowsApiSaveShowsUserOperationRequest {
  ids: string;
  saveShowsUserRequest?: SaveShowsUserRequest;
}

/**
 *
 */
export class ShowsApi extends runtime.BaseAPI {
  /**
   * Check if one or more shows is already saved in the current Spotify user\'s library.
   * Check User\'s Saved Shows
   */
  async checkUsersSavedShowsRaw(
    requestParameters: ShowsApiCheckUsersSavedShowsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<boolean>>> {
    if (requestParameters["ids"] == null) {
      throw new runtime.RequiredError(
        "ids",
        'Required parameter "ids" was null or undefined when calling checkUsersSavedShows().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["ids"] != null) {
      queryParameters["ids"] = requestParameters["ids"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-library-read"],
      );
    }

    let urlPath = `/me/shows/contains`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse<any>(response);
  }

  /**
   * Check if one or more shows is already saved in the current Spotify user\'s library.
   * Check User\'s Saved Shows
   */
  async checkUsersSavedShows(
    requestParameters: ShowsApiCheckUsersSavedShowsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<boolean>> {
    const response = await this.checkUsersSavedShowsRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Get Spotify catalog information for a single show identified by its unique Spotify ID.
   * Get Show
   */
  async getAShowRaw(
    requestParameters: ShowsApiGetAShowRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ShowObject>> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling getAShow().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["market"] != null) {
      queryParameters["market"] = requestParameters["market"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-read-playback-position"],
      );
    }

    let urlPath = `/shows/{id}`;
    urlPath = urlPath.replace(
      `{${"id"}}`,
      encodeURIComponent(String(requestParameters["id"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get Spotify catalog information for a single show identified by its unique Spotify ID.
   * Get Show
   */
  async getAShow(
    requestParameters: ShowsApiGetAShowRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ShowObject> {
    const response = await this.getAShowRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Get Spotify catalog information about an show’s episodes. Optional parameters can be used to limit the number of episodes returned.
   * Get Show Episodes
   */
  async getAShowsEpisodesRaw(
    requestParameters: ShowsApiGetAShowsEpisodesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PagingSimplifiedEpisodeObject>> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling getAShowsEpisodes().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["market"] != null) {
      queryParameters["market"] = requestParameters["market"];
    }

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    if (requestParameters["offset"] != null) {
      queryParameters["offset"] = requestParameters["offset"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-read-playback-position"],
      );
    }

    let urlPath = `/shows/{id}/episodes`;
    urlPath = urlPath.replace(
      `{${"id"}}`,
      encodeURIComponent(String(requestParameters["id"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get Spotify catalog information about an show’s episodes. Optional parameters can be used to limit the number of episodes returned.
   * Get Show Episodes
   */
  async getAShowsEpisodes(
    requestParameters: ShowsApiGetAShowsEpisodesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PagingSimplifiedEpisodeObject> {
    const response = await this.getAShowsEpisodesRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Get Spotify catalog information for several shows based on their Spotify IDs.
   * Get Several Shows
   */
  async getMultipleShowsRaw(
    requestParameters: ShowsApiGetMultipleShowsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<InlineObject13>> {
    if (requestParameters["ids"] == null) {
      throw new runtime.RequiredError(
        "ids",
        'Required parameter "ids" was null or undefined when calling getMultipleShows().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["market"] != null) {
      queryParameters["market"] = requestParameters["market"];
    }

    if (requestParameters["ids"] != null) {
      queryParameters["ids"] = requestParameters["ids"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        [],
      );
    }

    let urlPath = `/shows`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get Spotify catalog information for several shows based on their Spotify IDs.
   * Get Several Shows
   */
  async getMultipleShows(
    requestParameters: ShowsApiGetMultipleShowsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<InlineObject13> {
    const response = await this.getMultipleShowsRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Get a list of shows saved in the current Spotify user\'s library. Optional parameters can be used to limit the number of shows returned.
   * Get User\'s Saved Shows
   */
  async getUsersSavedShowsRaw(
    requestParameters: ShowsApiGetUsersSavedShowsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PagingSavedShowObject>> {
    const queryParameters: any = {};

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    if (requestParameters["offset"] != null) {
      queryParameters["offset"] = requestParameters["offset"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-library-read"],
      );
    }

    let urlPath = `/me/shows`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get a list of shows saved in the current Spotify user\'s library. Optional parameters can be used to limit the number of shows returned.
   * Get User\'s Saved Shows
   */
  async getUsersSavedShows(
    requestParameters: ShowsApiGetUsersSavedShowsRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PagingSavedShowObject> {
    const response = await this.getUsersSavedShowsRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Delete one or more shows from current Spotify user\'s library.
   * Remove User\'s Saved Shows
   */
  async removeShowsUserRaw(
    requestParameters: ShowsApiRemoveShowsUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["ids"] == null) {
      throw new runtime.RequiredError(
        "ids",
        'Required parameter "ids" was null or undefined when calling removeShowsUser().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["ids"] != null) {
      queryParameters["ids"] = requestParameters["ids"];
    }

    if (requestParameters["market"] != null) {
      queryParameters["market"] = requestParameters["market"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-library-modify"],
      );
    }

    let urlPath = `/me/shows`;

    const response = await this.request(
      {
        path: urlPath,
        method: "DELETE",
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters["saveShowsUserRequest"],
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Delete one or more shows from current Spotify user\'s library.
   * Remove User\'s Saved Shows
   */
  async removeShowsUser(
    requestParameters: ShowsApiRemoveShowsUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.removeShowsUserRaw(requestParameters, initOverrides);
  }

  /**
   * Save one or more shows to current Spotify user\'s library.
   * Save Shows for Current User
   */
  async saveShowsUserRaw(
    requestParameters: ShowsApiSaveShowsUserOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["ids"] == null) {
      throw new runtime.RequiredError(
        "ids",
        'Required parameter "ids" was null or undefined when calling saveShowsUser().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["ids"] != null) {
      queryParameters["ids"] = requestParameters["ids"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-library-modify"],
      );
    }

    let urlPath = `/me/shows`;

    const response = await this.request(
      {
        path: urlPath,
        method: "PUT",
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters["saveShowsUserRequest"],
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Save one or more shows to current Spotify user\'s library.
   * Save Shows for Current User
   */
  async saveShowsUser(
    requestParameters: ShowsApiSaveShowsUserOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.saveShowsUserRaw(requestParameters, initOverrides);
  }
}
