/* tslint:disable */
/* eslint-disable */
/**
 * Spotify Web API with fixes and improvements from sonallux
 * You can use Spotify\'s Web API to discover music and podcasts, manage your Spotify library, control audio playback, and much more. Browse our available Web API endpoints using the sidebar at left, or via the navigation bar on top of this page on smaller screens.  In order to make successful Web API requests your app will need a valid access token. One can be obtained through <a href=\"https://developer.spotify.com/documentation/general/guides/authorization-guide/\">OAuth 2.0</a>.  The base URI for all Web API requests is `https://api.spotify.com/v1`.  Need help? See our <a href=\"https://developer.spotify.com/documentation/web-api/guides/\">Web API guides</a> for more information, or visit the <a href=\"https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer\">Spotify for Developers community forum</a> to ask questions and connect with other developers.
 *
 * The version of the OpenAPI document: 2025.5.18
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
  FollowArtistsUsersRequest,
  FollowPlaylistRequest,
  FollowTypeEnum,
  GetAnAlbum401Response,
  GetFollowed200Response,
  GetFollowTypeEnum,
  PagingArtistObject,
  PagingPlaylistObject,
  PagingTrackObject,
  PrivateUserObject,
  PublicUserObject,
  UnfollowArtistsUsersRequest,
} from "../models/index";
import * as runtime from "../runtime";

export interface UsersApiCheckCurrentUserFollowsRequest {
  type: FollowTypeEnum;
  ids: string;
}

export interface UsersApiCheckIfUserFollowsPlaylistRequest {
  playlistId: string;
  ids?: string;
}

export interface UsersApiFollowArtistsUsersOperationRequest {
  type: FollowTypeEnum;
  ids: string;
  followArtistsUsersRequest?: FollowArtistsUsersRequest;
}

export interface UsersApiFollowPlaylistOperationRequest {
  playlistId: string;
  followPlaylistRequest?: FollowPlaylistRequest;
}

export interface UsersApiGetFollowedRequest {
  type: GetFollowTypeEnum;
  after?: string;
  limit?: number;
}

export interface UsersApiGetListUsersPlaylistsRequest {
  userId: string;
  limit?: number;
  offset?: number;
}

export interface UsersApiGetUsersProfileRequest {
  userId: string;
}

export interface UsersApiGetUsersTopArtistsRequest {
  timeRange?: string;
  limit?: number;
  offset?: number;
}

export interface UsersApiGetUsersTopTracksRequest {
  timeRange?: string;
  limit?: number;
  offset?: number;
}

export interface UsersApiUnfollowArtistsUsersOperationRequest {
  type: FollowTypeEnum;
  ids: string;
  unfollowArtistsUsersRequest?: UnfollowArtistsUsersRequest;
}

export interface UsersApiUnfollowPlaylistRequest {
  playlistId: string;
}

/**
 *
 */
export class UsersApi extends runtime.BaseAPI {
  /**
   * Check to see if the current user is following one or more artists or other Spotify users.
   * Check If User Follows Artists or Users
   */
  async checkCurrentUserFollowsRaw(
    requestParameters: UsersApiCheckCurrentUserFollowsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<boolean>>> {
    if (requestParameters["type"] == null) {
      throw new runtime.RequiredError(
        "type",
        'Required parameter "type" was null or undefined when calling checkCurrentUserFollows().',
      );
    }

    if (requestParameters["ids"] == null) {
      throw new runtime.RequiredError(
        "ids",
        'Required parameter "ids" was null or undefined when calling checkCurrentUserFollows().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["type"] != null) {
      queryParameters["type"] = requestParameters["type"];
    }

    if (requestParameters["ids"] != null) {
      queryParameters["ids"] = requestParameters["ids"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-follow-read"],
      );
    }

    let urlPath = `/me/following/contains`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse<any>(response);
  }

  /**
   * Check to see if the current user is following one or more artists or other Spotify users.
   * Check If User Follows Artists or Users
   */
  async checkCurrentUserFollows(
    requestParameters: UsersApiCheckCurrentUserFollowsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<boolean>> {
    const response = await this.checkCurrentUserFollowsRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Check to see if the current user is following a specified playlist.
   * Check if Current User Follows Playlist
   */
  async checkIfUserFollowsPlaylistRaw(
    requestParameters: UsersApiCheckIfUserFollowsPlaylistRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<boolean>>> {
    if (requestParameters["playlistId"] == null) {
      throw new runtime.RequiredError(
        "playlistId",
        'Required parameter "playlistId" was null or undefined when calling checkIfUserFollowsPlaylist().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["ids"] != null) {
      queryParameters["ids"] = requestParameters["ids"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        [],
      );
    }

    let urlPath = `/playlists/{playlist_id}/followers/contains`;
    urlPath = urlPath.replace(
      `{${"playlist_id"}}`,
      encodeURIComponent(String(requestParameters["playlistId"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse<any>(response);
  }

  /**
   * Check to see if the current user is following a specified playlist.
   * Check if Current User Follows Playlist
   */
  async checkIfUserFollowsPlaylist(
    requestParameters: UsersApiCheckIfUserFollowsPlaylistRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<boolean>> {
    const response = await this.checkIfUserFollowsPlaylistRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Add the current user as a follower of one or more artists or other Spotify users.
   * Follow Artists or Users
   */
  async followArtistsUsersRaw(
    requestParameters: UsersApiFollowArtistsUsersOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["type"] == null) {
      throw new runtime.RequiredError(
        "type",
        'Required parameter "type" was null or undefined when calling followArtistsUsers().',
      );
    }

    if (requestParameters["ids"] == null) {
      throw new runtime.RequiredError(
        "ids",
        'Required parameter "ids" was null or undefined when calling followArtistsUsers().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["type"] != null) {
      queryParameters["type"] = requestParameters["type"];
    }

    if (requestParameters["ids"] != null) {
      queryParameters["ids"] = requestParameters["ids"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-follow-modify"],
      );
    }

    let urlPath = `/me/following`;

    const response = await this.request(
      {
        path: urlPath,
        method: "PUT",
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters["followArtistsUsersRequest"],
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Add the current user as a follower of one or more artists or other Spotify users.
   * Follow Artists or Users
   */
  async followArtistsUsers(
    requestParameters: UsersApiFollowArtistsUsersOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.followArtistsUsersRaw(requestParameters, initOverrides);
  }

  /**
   * Add the current user as a follower of a playlist.
   * Follow Playlist
   */
  async followPlaylistRaw(
    requestParameters: UsersApiFollowPlaylistOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["playlistId"] == null) {
      throw new runtime.RequiredError(
        "playlistId",
        'Required parameter "playlistId" was null or undefined when calling followPlaylist().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["playlist-modify-public", "playlist-modify-private"],
      );
    }

    let urlPath = `/playlists/{playlist_id}/followers`;
    urlPath = urlPath.replace(
      `{${"playlist_id"}}`,
      encodeURIComponent(String(requestParameters["playlistId"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "PUT",
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters["followPlaylistRequest"],
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Add the current user as a follower of a playlist.
   * Follow Playlist
   */
  async followPlaylist(
    requestParameters: UsersApiFollowPlaylistOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.followPlaylistRaw(requestParameters, initOverrides);
  }

  /**
   * Get detailed profile information about the current user (including the current user\'s username).
   * Get Current User\'s Profile
   */
  async getCurrentUsersProfileRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PrivateUserObject>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-read-private", "user-read-email"],
      );
    }

    let urlPath = `/me`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get detailed profile information about the current user (including the current user\'s username).
   * Get Current User\'s Profile
   */
  async getCurrentUsersProfile(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PrivateUserObject> {
    const response = await this.getCurrentUsersProfileRaw(initOverrides);
    return await response.value();
  }

  /**
   * Get the current user\'s followed artists.
   * Get Followed Artists
   */
  async getFollowedRaw(
    requestParameters: UsersApiGetFollowedRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<GetFollowed200Response>> {
    if (requestParameters["type"] == null) {
      throw new runtime.RequiredError(
        "type",
        'Required parameter "type" was null or undefined when calling getFollowed().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["type"] != null) {
      queryParameters["type"] = requestParameters["type"];
    }

    if (requestParameters["after"] != null) {
      queryParameters["after"] = requestParameters["after"];
    }

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-follow-read"],
      );
    }

    let urlPath = `/me/following`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get the current user\'s followed artists.
   * Get Followed Artists
   */
  async getFollowed(
    requestParameters: UsersApiGetFollowedRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<GetFollowed200Response> {
    const response = await this.getFollowedRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Get a list of the playlists owned or followed by a Spotify user.
   * Get User\'s Playlists
   */
  async getListUsersPlaylistsRaw(
    requestParameters: UsersApiGetListUsersPlaylistsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PagingPlaylistObject>> {
    if (requestParameters["userId"] == null) {
      throw new runtime.RequiredError(
        "userId",
        'Required parameter "userId" was null or undefined when calling getListUsersPlaylists().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    if (requestParameters["offset"] != null) {
      queryParameters["offset"] = requestParameters["offset"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["playlist-read-private", "playlist-read-collaborative"],
      );
    }

    let urlPath = `/users/{user_id}/playlists`;
    urlPath = urlPath.replace(
      `{${"user_id"}}`,
      encodeURIComponent(String(requestParameters["userId"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get a list of the playlists owned or followed by a Spotify user.
   * Get User\'s Playlists
   */
  async getListUsersPlaylists(
    requestParameters: UsersApiGetListUsersPlaylistsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PagingPlaylistObject> {
    const response = await this.getListUsersPlaylistsRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Get public profile information about a Spotify user.
   * Get User\'s Profile
   */
  async getUsersProfileRaw(
    requestParameters: UsersApiGetUsersProfileRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PublicUserObject>> {
    if (requestParameters["userId"] == null) {
      throw new runtime.RequiredError(
        "userId",
        'Required parameter "userId" was null or undefined when calling getUsersProfile().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        [],
      );
    }

    let urlPath = `/users/{user_id}`;
    urlPath = urlPath.replace(
      `{${"user_id"}}`,
      encodeURIComponent(String(requestParameters["userId"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get public profile information about a Spotify user.
   * Get User\'s Profile
   */
  async getUsersProfile(
    requestParameters: UsersApiGetUsersProfileRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PublicUserObject> {
    const response = await this.getUsersProfileRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Get the current user\'s top artists based on calculated affinity.
   * Get User\'s Top Artists
   */
  async getUsersTopArtistsRaw(
    requestParameters: UsersApiGetUsersTopArtistsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PagingArtistObject>> {
    const queryParameters: any = {};

    if (requestParameters["timeRange"] != null) {
      queryParameters["time_range"] = requestParameters["timeRange"];
    }

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    if (requestParameters["offset"] != null) {
      queryParameters["offset"] = requestParameters["offset"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-top-read"],
      );
    }

    let urlPath = `/me/top/artists`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get the current user\'s top artists based on calculated affinity.
   * Get User\'s Top Artists
   */
  async getUsersTopArtists(
    requestParameters: UsersApiGetUsersTopArtistsRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PagingArtistObject> {
    const response = await this.getUsersTopArtistsRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Get the current user\'s top tracks based on calculated affinity.
   * Get User\'s Top Tracks
   */
  async getUsersTopTracksRaw(
    requestParameters: UsersApiGetUsersTopTracksRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PagingTrackObject>> {
    const queryParameters: any = {};

    if (requestParameters["timeRange"] != null) {
      queryParameters["time_range"] = requestParameters["timeRange"];
    }

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    if (requestParameters["offset"] != null) {
      queryParameters["offset"] = requestParameters["offset"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-top-read"],
      );
    }

    let urlPath = `/me/top/tracks`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get the current user\'s top tracks based on calculated affinity.
   * Get User\'s Top Tracks
   */
  async getUsersTopTracks(
    requestParameters: UsersApiGetUsersTopTracksRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PagingTrackObject> {
    const response = await this.getUsersTopTracksRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Remove the current user as a follower of one or more artists or other Spotify users.
   * Unfollow Artists or Users
   */
  async unfollowArtistsUsersRaw(
    requestParameters: UsersApiUnfollowArtistsUsersOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["type"] == null) {
      throw new runtime.RequiredError(
        "type",
        'Required parameter "type" was null or undefined when calling unfollowArtistsUsers().',
      );
    }

    if (requestParameters["ids"] == null) {
      throw new runtime.RequiredError(
        "ids",
        'Required parameter "ids" was null or undefined when calling unfollowArtistsUsers().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["type"] != null) {
      queryParameters["type"] = requestParameters["type"];
    }

    if (requestParameters["ids"] != null) {
      queryParameters["ids"] = requestParameters["ids"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-follow-modify"],
      );
    }

    let urlPath = `/me/following`;

    const response = await this.request(
      {
        path: urlPath,
        method: "DELETE",
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters["unfollowArtistsUsersRequest"],
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Remove the current user as a follower of one or more artists or other Spotify users.
   * Unfollow Artists or Users
   */
  async unfollowArtistsUsers(
    requestParameters: UsersApiUnfollowArtistsUsersOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.unfollowArtistsUsersRaw(requestParameters, initOverrides);
  }

  /**
   * Remove the current user as a follower of a playlist.
   * Unfollow Playlist
   */
  async unfollowPlaylistRaw(
    requestParameters: UsersApiUnfollowPlaylistRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["playlistId"] == null) {
      throw new runtime.RequiredError(
        "playlistId",
        'Required parameter "playlistId" was null or undefined when calling unfollowPlaylist().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["playlist-modify-public", "playlist-modify-private"],
      );
    }

    let urlPath = `/playlists/{playlist_id}/followers`;
    urlPath = urlPath.replace(
      `{${"playlist_id"}}`,
      encodeURIComponent(String(requestParameters["playlistId"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "DELETE",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Remove the current user as a follower of a playlist.
   * Unfollow Playlist
   */
  async unfollowPlaylist(
    requestParameters: UsersApiUnfollowPlaylistRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.unfollowPlaylistRaw(requestParameters, initOverrides);
  }
}
